//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BusinessType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Select One"/>
 *     &lt;enumeration value="Bank"/>
 *     &lt;enumeration value="Broker Dealer"/>
 *     &lt;enumeration value="Business Management"/>
 *     &lt;enumeration value="Central Bank"/>
 *     &lt;enumeration value="Charity/Foundation/Non-profit Organization"/>
 *     &lt;enumeration value="Commodity Pool Operator"/>
 *     &lt;enumeration value="Commodity Trading Advisor"/>
 *     &lt;enumeration value="Credit Union"/>
 *     &lt;enumeration value="Currency Dealer/ Exchanger"/>
 *     &lt;enumeration value="Educational Institution"/>
 *     &lt;enumeration value="ERISA Employee Benefit Plan"/>
 *     &lt;enumeration value="ERISA Retirement/Pension Plan"/>
 *     &lt;enumeration value="Estate"/>
 *     &lt;enumeration value="Federal/Sovereign Government Entity/Agency"/>
 *     &lt;enumeration value="Federal/Sovereign Government Retirement Plan"/>
 *     &lt;enumeration value="Futures Commission Merchant (FCM)"/>
 *     &lt;enumeration value="Grant Making Foundations"/>
 *     &lt;enumeration value="Hedge Fund"/>
 *     &lt;enumeration value="Indian Tribe"/>
 *     &lt;enumeration value="Insurance Company"/>
 *     &lt;enumeration value="Introducing Broker (Futures)"/>
 *     &lt;enumeration value="Investment Advisor"/>
 *     &lt;enumeration value="Investment Bank"/>
 *     &lt;enumeration value="Labor Union"/>
 *     &lt;enumeration value="Managed Care Organization (Health Insurance)"/>
 *     &lt;enumeration value="Modeling Agency"/>
 *     &lt;enumeration value="Money Manager"/>
 *     &lt;enumeration value="Money Transmitter"/>
 *     &lt;enumeration value="Mortgage Originator"/>
 *     &lt;enumeration value="Municipal/Local Government Entity/Agency"/>
 *     &lt;enumeration value="Municipal/Local Government Retirement Plan"/>
 *     &lt;enumeration value="Closed-end Mutual Fund"/>
 *     &lt;enumeration value="Non-ERISA Non-Trust Employee Benefit Plan"/>
 *     &lt;enumeration value="Non-ERISA Non-Trust Retirement/Pension Plan"/>
 *     &lt;enumeration value="Open-end Mutual Fund"/>
 *     &lt;enumeration value="Personal Holding Company (PHC)"/>
 *     &lt;enumeration value="Personal Investment Vehicle (PIV)"/>
 *     &lt;enumeration value="Portfolio Manager/ Portfolio Management Company"/>
 *     &lt;enumeration value="Private Equity Firm"/>
 *     &lt;enumeration value="Private Equity Fund"/>
 *     &lt;enumeration value="Property and Casualty Insurer"/>
 *     &lt;enumeration value="Proprietary Trading Firm"/>
 *     &lt;enumeration value="Real Estate Investment Trust (REIT)"/>
 *     &lt;enumeration value="Registered Investment Advisor (RIV)"/>
 *     &lt;enumeration value="Securities Firm"/>
 *     &lt;enumeration value="Sole Proprietorship"/>
 *     &lt;enumeration value="Special Purpose Vehicle (SPV)"/>
 *     &lt;enumeration value="State/Province Government Entity/Agency"/>
 *     &lt;enumeration value="State/Province Government Retirement Plan"/>
 *     &lt;enumeration value="Transportation Company"/>
 *     &lt;enumeration value="Tribal Authority"/>
 *     &lt;enumeration value="Trust"/>
 *     &lt;enumeration value="Underwriting Company"/>
 *     &lt;enumeration value="Unincorporated Organization/Association"/>
 *     &lt;enumeration value="Unregistered Investment Advisor"/>
 *     &lt;enumeration value="Venture Capital Firm"/>
 *     &lt;enumeration value="Venture Capital Fund"/>
 *     &lt;enumeration value="Basic Materials"/>
 *     &lt;enumeration value="Consumer Goods"/>
 *     &lt;enumeration value="Healthcare"/>
 *     &lt;enumeration value="Industrial Goods"/>
 *     &lt;enumeration value="Services"/>
 *     &lt;enumeration value="Technology"/>
 *     &lt;enumeration value="Utilities"/>
 *     &lt;enumeration value="Non-ERISA Trust Employee Benefit Plan"/>
 *     &lt;enumeration value="Non-ERISA Trust Retirement/Pension Plan"/>
 *     &lt;enumeration value="Investment Manager"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BusinessType")
@XmlEnum
public enum BusinessType {

    @XmlEnumValue("Select One")
    SELECT_ONE("Select One"),
    @XmlEnumValue("Bank")
    BANK("Bank"),
    @XmlEnumValue("Broker Dealer")
    BROKER_DEALER("Broker Dealer"),
    @XmlEnumValue("Business Management")
    BUSINESS_MANAGEMENT("Business Management"),
    @XmlEnumValue("Central Bank")
    CENTRAL_BANK("Central Bank"),
    @XmlEnumValue("Charity/Foundation/Non-profit Organization")
    CHARITY_FOUNDATION_NON_PROFIT_ORGANIZATION("Charity/Foundation/Non-profit Organization"),
    @XmlEnumValue("Commodity Pool Operator")
    COMMODITY_POOL_OPERATOR("Commodity Pool Operator"),
    @XmlEnumValue("Commodity Trading Advisor")
    COMMODITY_TRADING_ADVISOR("Commodity Trading Advisor"),
    @XmlEnumValue("Credit Union")
    CREDIT_UNION("Credit Union"),
    @XmlEnumValue("Currency Dealer/ Exchanger")
    CURRENCY_DEALER_EXCHANGER("Currency Dealer/ Exchanger"),
    @XmlEnumValue("Educational Institution")
    EDUCATIONAL_INSTITUTION("Educational Institution"),
    @XmlEnumValue("ERISA Employee Benefit Plan")
    ERISA_EMPLOYEE_BENEFIT_PLAN("ERISA Employee Benefit Plan"),
    @XmlEnumValue("ERISA Retirement/Pension Plan")
    ERISA_RETIREMENT_PENSION_PLAN("ERISA Retirement/Pension Plan"),
    @XmlEnumValue("Estate")
    ESTATE("Estate"),
    @XmlEnumValue("Federal/Sovereign Government Entity/Agency")
    FEDERAL_SOVEREIGN_GOVERNMENT_ENTITY_AGENCY("Federal/Sovereign Government Entity/Agency"),
    @XmlEnumValue("Federal/Sovereign Government Retirement Plan")
    FEDERAL_SOVEREIGN_GOVERNMENT_RETIREMENT_PLAN("Federal/Sovereign Government Retirement Plan"),
    @XmlEnumValue("Futures Commission Merchant (FCM)")
    FUTURES_COMMISSION_MERCHANT_FCM("Futures Commission Merchant (FCM)"),
    @XmlEnumValue("Grant Making Foundations")
    GRANT_MAKING_FOUNDATIONS("Grant Making Foundations"),
    @XmlEnumValue("Hedge Fund")
    HEDGE_FUND("Hedge Fund"),
    @XmlEnumValue("Indian Tribe")
    INDIAN_TRIBE("Indian Tribe"),
    @XmlEnumValue("Insurance Company")
    INSURANCE_COMPANY("Insurance Company"),
    @XmlEnumValue("Introducing Broker (Futures)")
    INTRODUCING_BROKER_FUTURES("Introducing Broker (Futures)"),
    @XmlEnumValue("Investment Advisor")
    INVESTMENT_ADVISOR("Investment Advisor"),
    @XmlEnumValue("Investment Bank")
    INVESTMENT_BANK("Investment Bank"),
    @XmlEnumValue("Labor Union")
    LABOR_UNION("Labor Union"),
    @XmlEnumValue("Managed Care Organization (Health Insurance)")
    MANAGED_CARE_ORGANIZATION_HEALTH_INSURANCE("Managed Care Organization (Health Insurance)"),
    @XmlEnumValue("Modeling Agency")
    MODELING_AGENCY("Modeling Agency"),
    @XmlEnumValue("Money Manager")
    MONEY_MANAGER("Money Manager"),
    @XmlEnumValue("Money Transmitter")
    MONEY_TRANSMITTER("Money Transmitter"),
    @XmlEnumValue("Mortgage Originator")
    MORTGAGE_ORIGINATOR("Mortgage Originator"),
    @XmlEnumValue("Municipal/Local Government Entity/Agency")
    MUNICIPAL_LOCAL_GOVERNMENT_ENTITY_AGENCY("Municipal/Local Government Entity/Agency"),
    @XmlEnumValue("Municipal/Local Government Retirement Plan")
    MUNICIPAL_LOCAL_GOVERNMENT_RETIREMENT_PLAN("Municipal/Local Government Retirement Plan"),
    @XmlEnumValue("Closed-end Mutual Fund")
    CLOSED_END_MUTUAL_FUND("Closed-end Mutual Fund"),
    @XmlEnumValue("Non-ERISA Non-Trust Employee Benefit Plan")
    NON_ERISA_NON_TRUST_EMPLOYEE_BENEFIT_PLAN("Non-ERISA Non-Trust Employee Benefit Plan"),
    @XmlEnumValue("Non-ERISA Non-Trust Retirement/Pension Plan")
    NON_ERISA_NON_TRUST_RETIREMENT_PENSION_PLAN("Non-ERISA Non-Trust Retirement/Pension Plan"),
    @XmlEnumValue("Open-end Mutual Fund")
    OPEN_END_MUTUAL_FUND("Open-end Mutual Fund"),
    @XmlEnumValue("Personal Holding Company (PHC)")
    PERSONAL_HOLDING_COMPANY_PHC("Personal Holding Company (PHC)"),
    @XmlEnumValue("Personal Investment Vehicle (PIV)")
    PERSONAL_INVESTMENT_VEHICLE_PIV("Personal Investment Vehicle (PIV)"),
    @XmlEnumValue("Portfolio Manager/ Portfolio Management Company")
    PORTFOLIO_MANAGER_PORTFOLIO_MANAGEMENT_COMPANY("Portfolio Manager/ Portfolio Management Company"),
    @XmlEnumValue("Private Equity Firm")
    PRIVATE_EQUITY_FIRM("Private Equity Firm"),
    @XmlEnumValue("Private Equity Fund")
    PRIVATE_EQUITY_FUND("Private Equity Fund"),
    @XmlEnumValue("Property and Casualty Insurer")
    PROPERTY_AND_CASUALTY_INSURER("Property and Casualty Insurer"),
    @XmlEnumValue("Proprietary Trading Firm")
    PROPRIETARY_TRADING_FIRM("Proprietary Trading Firm"),
    @XmlEnumValue("Real Estate Investment Trust (REIT)")
    REAL_ESTATE_INVESTMENT_TRUST_REIT("Real Estate Investment Trust (REIT)"),
    @XmlEnumValue("Registered Investment Advisor (RIV)")
    REGISTERED_INVESTMENT_ADVISOR_RIV("Registered Investment Advisor (RIV)"),
    @XmlEnumValue("Securities Firm")
    SECURITIES_FIRM("Securities Firm"),
    @XmlEnumValue("Sole Proprietorship")
    SOLE_PROPRIETORSHIP("Sole Proprietorship"),
    @XmlEnumValue("Special Purpose Vehicle (SPV)")
    SPECIAL_PURPOSE_VEHICLE_SPV("Special Purpose Vehicle (SPV)"),
    @XmlEnumValue("State/Province Government Entity/Agency")
    STATE_PROVINCE_GOVERNMENT_ENTITY_AGENCY("State/Province Government Entity/Agency"),
    @XmlEnumValue("State/Province Government Retirement Plan")
    STATE_PROVINCE_GOVERNMENT_RETIREMENT_PLAN("State/Province Government Retirement Plan"),
    @XmlEnumValue("Transportation Company")
    TRANSPORTATION_COMPANY("Transportation Company"),
    @XmlEnumValue("Tribal Authority")
    TRIBAL_AUTHORITY("Tribal Authority"),
    @XmlEnumValue("Trust")
    TRUST("Trust"),
    @XmlEnumValue("Underwriting Company")
    UNDERWRITING_COMPANY("Underwriting Company"),
    @XmlEnumValue("Unincorporated Organization/Association")
    UNINCORPORATED_ORGANIZATION_ASSOCIATION("Unincorporated Organization/Association"),
    @XmlEnumValue("Unregistered Investment Advisor")
    UNREGISTERED_INVESTMENT_ADVISOR("Unregistered Investment Advisor"),
    @XmlEnumValue("Venture Capital Firm")
    VENTURE_CAPITAL_FIRM("Venture Capital Firm"),
    @XmlEnumValue("Venture Capital Fund")
    VENTURE_CAPITAL_FUND("Venture Capital Fund"),
    @XmlEnumValue("Basic Materials")
    BASIC_MATERIALS("Basic Materials"),
    @XmlEnumValue("Consumer Goods")
    CONSUMER_GOODS("Consumer Goods"),
    @XmlEnumValue("Healthcare")
    HEALTHCARE("Healthcare"),
    @XmlEnumValue("Industrial Goods")
    INDUSTRIAL_GOODS("Industrial Goods"),
    @XmlEnumValue("Services")
    SERVICES("Services"),
    @XmlEnumValue("Technology")
    TECHNOLOGY("Technology"),
    @XmlEnumValue("Utilities")
    UTILITIES("Utilities"),
    @XmlEnumValue("Non-ERISA Trust Employee Benefit Plan")
    NON_ERISA_TRUST_EMPLOYEE_BENEFIT_PLAN("Non-ERISA Trust Employee Benefit Plan"),
    @XmlEnumValue("Non-ERISA Trust Retirement/Pension Plan")
    NON_ERISA_TRUST_RETIREMENT_PENSION_PLAN("Non-ERISA Trust Retirement/Pension Plan"),
    @XmlEnumValue("Investment Manager")
    INVESTMENT_MANAGER("Investment Manager");
    private final String value;

    BusinessType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BusinessType fromValue(String v) {
        for (BusinessType c: BusinessType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
