//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Exchanges complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Exchanges">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Exchange" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{www.headstrong.com/common}CmAttributeString"/>
 *                   &lt;element name="Country" type="{www.headstrong.com/common}CmAttributeCountry"/>
 *                   &lt;element name="TickerSymbol" type="{www.headstrong.com/common}CmAttributeString"/>
 *                   &lt;element name="IsPrimary" type="{www.headstrong.com/common}CmAttributeOption"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Exchanges", propOrder = {
    "exchange"
})
public class Exchanges
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Exchange")
    protected List<Exchanges.Exchange> exchange;

    /**
     * Gets the value of the exchange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exchange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExchange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Exchanges.Exchange }
     * 
     * 
     */
    public List<Exchanges.Exchange> getExchange() {
        if (exchange == null) {
            exchange = new ArrayList<Exchanges.Exchange>();
        }
        return this.exchange;
    }

    public void setExchange(List<Exchanges.Exchange> value) {
        this.exchange = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{www.headstrong.com/common}CmAttributeString"/>
     *         &lt;element name="Country" type="{www.headstrong.com/common}CmAttributeCountry"/>
     *         &lt;element name="TickerSymbol" type="{www.headstrong.com/common}CmAttributeString"/>
     *         &lt;element name="IsPrimary" type="{www.headstrong.com/common}CmAttributeOption"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "country",
        "tickerSymbol",
        "isPrimary"
    })
    public static class Exchange
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "Name", required = true)
        protected CmAttributeString name;
        @XmlElement(name = "Country", required = true)
        protected CmAttributeCountry country;
        @XmlElement(name = "TickerSymbol", required = true)
        protected CmAttributeString tickerSymbol;
        @XmlElement(name = "IsPrimary", required = true)
        protected CmAttributeOption isPrimary;
        @XmlAttribute
        protected Integer id;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link CmAttributeString }
         *     
         */
        public CmAttributeString getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link CmAttributeString }
         *     
         */
        public void setName(CmAttributeString value) {
            this.name = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link CmAttributeCountry }
         *     
         */
        public CmAttributeCountry getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link CmAttributeCountry }
         *     
         */
        public void setCountry(CmAttributeCountry value) {
            this.country = value;
        }

        /**
         * Gets the value of the tickerSymbol property.
         * 
         * @return
         *     possible object is
         *     {@link CmAttributeString }
         *     
         */
        public CmAttributeString getTickerSymbol() {
            return tickerSymbol;
        }

        /**
         * Sets the value of the tickerSymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link CmAttributeString }
         *     
         */
        public void setTickerSymbol(CmAttributeString value) {
            this.tickerSymbol = value;
        }

        /**
         * Gets the value of the isPrimary property.
         * 
         * @return
         *     possible object is
         *     {@link CmAttributeOption }
         *     
         */
        public CmAttributeOption getIsPrimary() {
            return isPrimary;
        }

        /**
         * Sets the value of the isPrimary property.
         * 
         * @param value
         *     allowed object is
         *     {@link CmAttributeOption }
         *     
         */
        public void setIsPrimary(CmAttributeOption value) {
            this.isPrimary = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }

    }

}
