//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HierachyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HierachyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Select One"/>
 *     &lt;enumeration value="Legal"/>
 *     &lt;enumeration value="Credit"/>
 *     &lt;enumeration value="Sales"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HierachyType")
@XmlEnum
public enum HierachyType {

    @XmlEnumValue("Select One")
    SELECT_ONE("Select One"),
    @XmlEnumValue("Legal")
    LEGAL("Legal"),
    @XmlEnumValue("Credit")
    CREDIT("Credit"),
    @XmlEnumValue("Sales")
    SALES("Sales");
    private final String value;

    HierachyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HierachyType fromValue(String v) {
        for (HierachyType c: HierachyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
