//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndustryClassification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndustryClassification">
 *   &lt;complexContent>
 *     &lt;extension base="{www.headstrong.com/common}CmAttribute">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Type" type="{www.headstrong.com/common}IndustryClassificationType" minOccurs="0"/>
 *         &lt;element name="Value" type="{www.headstrong.com/common}CmAttributeString" minOccurs="0"/>
 *         &lt;element name="Desc" type="{www.headstrong.com/common}CmAttributeString"/>
 *         &lt;element name="IsPrimary" type="{www.headstrong.com/common}CmAttributeOption"/>
 *         &lt;element name="Code" type="{www.headstrong.com/common}CmAttributeString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndustryClassification", propOrder = {
    "id",
    "type",
    "value",
    "desc",
    "isPrimary",
    "code"
})
public class IndustryClassification
    extends CmAttribute
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String id;
    @XmlElement(name = "Type")
    protected IndustryClassificationType type;
    @XmlElement(name = "Value")
    protected CmAttributeString value;
    @XmlElement(name = "Desc", required = true)
    protected CmAttributeString desc;
    @XmlElement(name = "IsPrimary", required = true)
    protected CmAttributeOption isPrimary;
    @XmlElement(name = "Code")
    protected CmAttributeString code;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link IndustryClassificationType }
     *     
     */
    public IndustryClassificationType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndustryClassificationType }
     *     
     */
    public void setType(IndustryClassificationType value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link CmAttributeString }
     *     
     */
    public CmAttributeString getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link CmAttributeString }
     *     
     */
    public void setValue(CmAttributeString value) {
        this.value = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link CmAttributeString }
     *     
     */
    public CmAttributeString getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link CmAttributeString }
     *     
     */
    public void setDesc(CmAttributeString value) {
        this.desc = value;
    }

    /**
     * Gets the value of the isPrimary property.
     * 
     * @return
     *     possible object is
     *     {@link CmAttributeOption }
     *     
     */
    public CmAttributeOption getIsPrimary() {
        return isPrimary;
    }

    /**
     * Sets the value of the isPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CmAttributeOption }
     *     
     */
    public void setIsPrimary(CmAttributeOption value) {
        this.isPrimary = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CmAttributeString }
     *     
     */
    public CmAttributeString getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CmAttributeString }
     *     
     */
    public void setCode(CmAttributeString value) {
        this.code = value;
    }

}
