//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.headstrong.npi.raas.xml.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.headstrong.npi.raas.xml.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entity.ListedInformation }
     * 
     */
    public Entity.ListedInformation createEntityListedInformation() {
        return new Entity.ListedInformation();
    }

    /**
     * Create an instance of {@link Entity.BusinessActivities }
     * 
     */
    public Entity.BusinessActivities createEntityBusinessActivities() {
        return new Entity.BusinessActivities();
    }

    /**
     * Create an instance of {@link Regulators }
     * 
     */
    public Regulators createRegulators() {
        return new Regulators();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link RemediationProfile.Risk.OriginalRisk }
     * 
     */
    public RemediationProfile.Risk.OriginalRisk createRemediationProfileRiskOriginalRisk() {
        return new RemediationProfile.Risk.OriginalRisk();
    }

    /**
     * Create an instance of {@link Entity.ControllerAndDirector }
     * 
     */
    public Entity.ControllerAndDirector createEntityControllerAndDirector() {
        return new Entity.ControllerAndDirector();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Entity.Ownership.OwnershipIndividual }
     * 
     */
    public Entity.Ownership.OwnershipIndividual createEntityOwnershipOwnershipIndividual() {
        return new Entity.Ownership.OwnershipIndividual();
    }

    /**
     * Create an instance of {@link RemediationProfile.Risk.CalculatedRisk }
     * 
     */
    public RemediationProfile.Risk.CalculatedRisk createRemediationProfileRiskCalculatedRisk() {
        return new RemediationProfile.Risk.CalculatedRisk();
    }

    /**
     * Create an instance of {@link Entity.Formation }
     * 
     */
    public Entity.Formation createEntityFormation() {
        return new Entity.Formation();
    }

    /**
     * Create an instance of {@link CmAttributeEntityType }
     * 
     */
    public CmAttributeEntityType createCmAttributeEntityType() {
        return new CmAttributeEntityType();
    }

    /**
     * Create an instance of {@link KYCOwner }
     * 
     */
    public KYCOwner createKYCOwner() {
        return new KYCOwner();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link Entity.RelatedPartyInformation }
     * 
     */
    public Entity.RelatedPartyInformation createEntityRelatedPartyInformation() {
        return new Entity.RelatedPartyInformation();
    }

    /**
     * Create an instance of {@link CmAttributeTime }
     * 
     */
    public CmAttributeTime createCmAttributeTime() {
        return new CmAttributeTime();
    }

    /**
     * Create an instance of {@link Regulators.Regulator }
     * 
     */
    public Regulators.Regulator createRegulatorsRegulator() {
        return new Regulators.Regulator();
    }

    /**
     * Create an instance of {@link RemediationProfile.Risk.CalculatedRisk.Score }
     * 
     */
    public RemediationProfile.Risk.CalculatedRisk.Score createRemediationProfileRiskCalculatedRiskScore() {
        return new RemediationProfile.Risk.CalculatedRisk.Score();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link RemediationProfile.Risk.FinalRisk }
     * 
     */
    public RemediationProfile.Risk.FinalRisk createRemediationProfileRiskFinalRisk() {
        return new RemediationProfile.Risk.FinalRisk();
    }

    /**
     * Create an instance of {@link Entity.RegistrationInformation }
     * 
     */
    public Entity.RegistrationInformation createEntityRegistrationInformation() {
        return new Entity.RegistrationInformation();
    }

    /**
     * Create an instance of {@link TaxInfo }
     * 
     */
    public TaxInfo createTaxInfo() {
        return new TaxInfo();
    }

    /**
     * Create an instance of {@link CmAttributeDate }
     * 
     */
    public CmAttributeDate createCmAttributeDate() {
        return new CmAttributeDate();
    }

    /**
     * Create an instance of {@link CmAttributeOption }
     * 
     */
    public CmAttributeOption createCmAttributeOption() {
        return new CmAttributeOption();
    }

    /**
     * Create an instance of {@link Entity.LegalHierachy.Hierachy }
     * 
     */
    public Entity.LegalHierachy.Hierachy createEntityLegalHierachyHierachy() {
        return new Entity.LegalHierachy.Hierachy();
    }

    /**
     * Create an instance of {@link CmAttributeInt }
     * 
     */
    public CmAttributeInt createCmAttributeInt() {
        return new CmAttributeInt();
    }

    /**
     * Create an instance of {@link Entity.EntityNames }
     * 
     */
    public Entity.EntityNames createEntityEntityNames() {
        return new Entity.EntityNames();
    }

    /**
     * Create an instance of {@link CmAttributeLegalForm }
     * 
     */
    public CmAttributeLegalForm createCmAttributeLegalForm() {
        return new CmAttributeLegalForm();
    }

    /**
     * Create an instance of {@link Entity.TradingInformation }
     * 
     */
    public Entity.TradingInformation createEntityTradingInformation() {
        return new Entity.TradingInformation();
    }

    /**
     * Create an instance of {@link RemediationProfile }
     * 
     */
    public RemediationProfile createRemediationProfile() {
        return new RemediationProfile();
    }

    /**
     * Create an instance of {@link Entity.ContactInformation }
     * 
     */
    public Entity.ContactInformation createEntityContactInformation() {
        return new Entity.ContactInformation();
    }

    /**
     * Create an instance of {@link FileStatusInfo.CurrentStatus }
     * 
     */
    public FileStatusInfo.CurrentStatus createFileStatusInfoCurrentStatus() {
        return new FileStatusInfo.CurrentStatus();
    }

    /**
     * Create an instance of {@link RemediationProfile.Risk }
     * 
     */
    public RemediationProfile.Risk createRemediationProfileRisk() {
        return new RemediationProfile.Risk();
    }

    /**
     * Create an instance of {@link GovtIDInfo }
     * 
     */
    public GovtIDInfo createGovtIDInfo() {
        return new GovtIDInfo();
    }

    /**
     * Create an instance of {@link CmAttributeGender }
     * 
     */
    public CmAttributeGender createCmAttributeGender() {
        return new CmAttributeGender();
    }

    /**
     * Create an instance of {@link Entity.RelatedPartyInformation.RelatedPartyIndividual }
     * 
     */
    public Entity.RelatedPartyInformation.RelatedPartyIndividual createEntityRelatedPartyInformationRelatedPartyIndividual() {
        return new Entity.RelatedPartyInformation.RelatedPartyIndividual();
    }

    /**
     * Create an instance of {@link CmAttributeOwnershipType }
     * 
     */
    public CmAttributeOwnershipType createCmAttributeOwnershipType() {
        return new CmAttributeOwnershipType();
    }

    /**
     * Create an instance of {@link CmAttributePartyType }
     * 
     */
    public CmAttributePartyType createCmAttributePartyType() {
        return new CmAttributePartyType();
    }

    /**
     * Create an instance of {@link CmAttributeWebsiteAddressType }
     * 
     */
    public CmAttributeWebsiteAddressType createCmAttributeWebsiteAddressType() {
        return new CmAttributeWebsiteAddressType();
    }

    /**
     * Create an instance of {@link Entity.FinancialInformation }
     * 
     */
    public Entity.FinancialInformation createEntityFinancialInformation() {
        return new Entity.FinancialInformation();
    }

    /**
     * Create an instance of {@link Entity.LegalHierachy }
     * 
     */
    public Entity.LegalHierachy createEntityLegalHierachy() {
        return new Entity.LegalHierachy();
    }

    /**
     * Create an instance of {@link ReferenceDocuments }
     * 
     */
    public ReferenceDocuments createReferenceDocuments() {
        return new ReferenceDocuments();
    }

    /**
     * Create an instance of {@link Entity.RegulatorInformation }
     * 
     */
    public Entity.RegulatorInformation createEntityRegulatorInformation() {
        return new Entity.RegulatorInformation();
    }

    /**
     * Create an instance of {@link Entity.LicenseInformation }
     * 
     */
    public Entity.LicenseInformation createEntityLicenseInformation() {
        return new Entity.LicenseInformation();
    }

    /**
     * Create an instance of {@link CmAttributeMiFIDClassifications }
     * 
     */
    public CmAttributeMiFIDClassifications createCmAttributeMiFIDClassifications() {
        return new CmAttributeMiFIDClassifications();
    }

    /**
     * Create an instance of {@link Entity.CompanyAML }
     * 
     */
    public Entity.CompanyAML createEntityCompanyAML() {
        return new Entity.CompanyAML();
    }

    /**
     * Create an instance of {@link Comments }
     * 
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link RemediationProfile.ProfileStatusInfo.CurrentStatus }
     * 
     */
    public RemediationProfile.ProfileStatusInfo.CurrentStatus createRemediationProfileProfileStatusInfoCurrentStatus() {
        return new RemediationProfile.ProfileStatusInfo.CurrentStatus();
    }

    /**
     * Create an instance of {@link Entity.BearerShares }
     * 
     */
    public Entity.BearerShares createEntityBearerShares() {
        return new Entity.BearerShares();
    }

    /**
     * Create an instance of {@link Entity.Ownership.OwnershipCorporate }
     * 
     */
    public Entity.Ownership.OwnershipCorporate createEntityOwnershipOwnershipCorporate() {
        return new Entity.Ownership.OwnershipCorporate();
    }

    /**
     * Create an instance of {@link Entity.GovernmentOwnershipInfo }
     * 
     */
    public Entity.GovernmentOwnershipInfo createEntityGovernmentOwnershipInfo() {
        return new Entity.GovernmentOwnershipInfo();
    }

    /**
     * Create an instance of {@link RemediationProfile.RefData }
     * 
     */
    public RemediationProfile.RefData createRemediationProfileRefData() {
        return new RemediationProfile.RefData();
    }

    /**
     * Create an instance of {@link ExternalIdentifiers }
     * 
     */
    public ExternalIdentifiers createExternalIdentifiers() {
        return new ExternalIdentifiers();
    }

    /**
     * Create an instance of {@link CmAttributeBoolean }
     * 
     */
    public CmAttributeBoolean createCmAttributeBoolean() {
        return new CmAttributeBoolean();
    }

    /**
     * Create an instance of {@link RemediationFile }
     * 
     */
    public RemediationFile createRemediationFile() {
        return new RemediationFile();
    }

    /**
     * Create an instance of {@link RemediationProfile.ProfileStatusInfo.CurrentState }
     * 
     */
    public RemediationProfile.ProfileStatusInfo.CurrentState createRemediationProfileProfileStatusInfoCurrentState() {
        return new RemediationProfile.ProfileStatusInfo.CurrentState();
    }

    /**
     * Create an instance of {@link Entity.RelatedPartyInformation.RelatedPartyNonIndividual }
     * 
     */
    public Entity.RelatedPartyInformation.RelatedPartyNonIndividual createEntityRelatedPartyInformationRelatedPartyNonIndividual() {
        return new Entity.RelatedPartyInformation.RelatedPartyNonIndividual();
    }

    /**
     * Create an instance of {@link CmAttributeString }
     * 
     */
    public CmAttributeString createCmAttributeString() {
        return new CmAttributeString();
    }

    /**
     * Create an instance of {@link FileStatusInfo }
     * 
     */
    public FileStatusInfo createFileStatusInfo() {
        return new FileStatusInfo();
    }

    /**
     * Create an instance of {@link CmAttributeLong }
     * 
     */
    public CmAttributeLong createCmAttributeLong() {
        return new CmAttributeLong();
    }

    /**
     * Create an instance of {@link Entity.WebsiteAddresses.WebsiteAddress }
     * 
     */
    public Entity.WebsiteAddresses.WebsiteAddress createEntityWebsiteAddressesWebsiteAddress() {
        return new Entity.WebsiteAddresses.WebsiteAddress();
    }

    /**
     * Create an instance of {@link CmAttributeCurrency }
     * 
     */
    public CmAttributeCurrency createCmAttributeCurrency() {
        return new CmAttributeCurrency();
    }

    /**
     * Create an instance of {@link EntityAliases }
     * 
     */
    public EntityAliases createEntityAliases() {
        return new EntityAliases();
    }

    /**
     * Create an instance of {@link CmAttributeInteger }
     * 
     */
    public CmAttributeInteger createCmAttributeInteger() {
        return new CmAttributeInteger();
    }

    /**
     * Create an instance of {@link CmAttributeDateMonthDay }
     * 
     */
    public CmAttributeDateMonthDay createCmAttributeDateMonthDay() {
        return new CmAttributeDateMonthDay();
    }

    /**
     * Create an instance of {@link CmAttributeDateTime }
     * 
     */
    public CmAttributeDateTime createCmAttributeDateTime() {
        return new CmAttributeDateTime();
    }

    /**
     * Create an instance of {@link CmAttributeDouble }
     * 
     */
    public CmAttributeDouble createCmAttributeDouble() {
        return new CmAttributeDouble();
    }

    /**
     * Create an instance of {@link ReferenceDocuments.Document }
     * 
     */
    public ReferenceDocuments.Document createReferenceDocumentsDocument() {
        return new ReferenceDocuments.Document();
    }

    /**
     * Create an instance of {@link IndustryClassification }
     * 
     */
    public IndustryClassification createIndustryClassification() {
        return new IndustryClassification();
    }

    /**
     * Create an instance of {@link Exchanges.Exchange }
     * 
     */
    public Exchanges.Exchange createExchangesExchange() {
        return new Exchanges.Exchange();
    }

    /**
     * Create an instance of {@link RemediationProfile.ProfileStatusInfo }
     * 
     */
    public RemediationProfile.ProfileStatusInfo createRemediationProfileProfileStatusInfo() {
        return new RemediationProfile.ProfileStatusInfo();
    }

    /**
     * Create an instance of {@link CmAttributeCountry }
     * 
     */
    public CmAttributeCountry createCmAttributeCountry() {
        return new CmAttributeCountry();
    }

    /**
     * Create an instance of {@link Entity.Ownership }
     * 
     */
    public Entity.Ownership createEntityOwnership() {
        return new Entity.Ownership();
    }

    /**
     * Create an instance of {@link Entity.LegalHierachy.Hierachy.Parent }
     * 
     */
    public Entity.LegalHierachy.Hierachy.Parent createEntityLegalHierachyHierachyParent() {
        return new Entity.LegalHierachy.Hierachy.Parent();
    }

    /**
     * Create an instance of {@link Entity.CoreInformation }
     * 
     */
    public Entity.CoreInformation createEntityCoreInformation() {
        return new Entity.CoreInformation();
    }

    /**
     * Create an instance of {@link Entity.RegulatedInformation }
     * 
     */
    public Entity.RegulatedInformation createEntityRegulatedInformation() {
        return new Entity.RegulatedInformation();
    }

    /**
     * Create an instance of {@link Exchanges }
     * 
     */
    public Exchanges createExchanges() {
        return new Exchanges();
    }

    /**
     * Create an instance of {@link Entity.ControllerAndDirector.ControllersAndDirectors }
     * 
     */
    public Entity.ControllerAndDirector.ControllersAndDirectors createEntityControllerAndDirectorControllersAndDirectors() {
        return new Entity.ControllerAndDirector.ControllersAndDirectors();
    }

    /**
     * Create an instance of {@link Entity.PlaceOfBusiness }
     * 
     */
    public Entity.PlaceOfBusiness createEntityPlaceOfBusiness() {
        return new Entity.PlaceOfBusiness();
    }

    /**
     * Create an instance of {@link Entity.WebsiteAddresses }
     * 
     */
    public Entity.WebsiteAddresses createEntityWebsiteAddresses() {
        return new Entity.WebsiteAddresses();
    }

    /**
     * Create an instance of {@link CountryOfBusiness }
     * 
     */
    public CountryOfBusiness createCountryOfBusiness() {
        return new CountryOfBusiness();
    }

}
