//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PartyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Select One"/>
 *     &lt;enumeration value="Client"/>
 *     &lt;enumeration value="Beneficial Owners (Corp.)"/>
 *     &lt;enumeration value="Beneficial Owners (Indiv.)"/>
 *     &lt;enumeration value="Controllers (Corp.)"/>
 *     &lt;enumeration value="Controllers (Indiv.)"/>
 *     &lt;enumeration value="Related Parties (Entity)"/>
 *     &lt;enumeration value="Related Parties (Indiv.)"/>
 *     &lt;enumeration value="Direct Appointees"/>
 *     &lt;enumeration value="Other Entities"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PartyType")
@XmlEnum
public enum PartyType {

    @XmlEnumValue("Select One")
    SELECT_ONE("Select One"),
    @XmlEnumValue("Client")
    CLIENT("Client"),
    @XmlEnumValue("Beneficial Owners (Corp.)")
    BENEFICIAL_OWNERS_CORP("Beneficial Owners (Corp.)"),
    @XmlEnumValue("Beneficial Owners (Indiv.)")
    BENEFICIAL_OWNERS_INDIV("Beneficial Owners (Indiv.)"),
    @XmlEnumValue("Controllers (Corp.)")
    CONTROLLERS_CORP("Controllers (Corp.)"),
    @XmlEnumValue("Controllers (Indiv.)")
    CONTROLLERS_INDIV("Controllers (Indiv.)"),
    @XmlEnumValue("Related Parties (Entity)")
    RELATED_PARTIES_ENTITY("Related Parties (Entity)"),
    @XmlEnumValue("Related Parties (Indiv.)")
    RELATED_PARTIES_INDIV("Related Parties (Indiv.)"),
    @XmlEnumValue("Direct Appointees")
    DIRECT_APPOINTEES("Direct Appointees"),
    @XmlEnumValue("Other Entities")
    OTHER_ENTITIES("Other Entities");
    private final String value;

    PartyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PartyType fromValue(String v) {
        for (PartyType c: PartyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
