//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RemediationProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemediationProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileStatusInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CurrentStatus">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Current_State" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Owner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CaseNotes" type="{www.headstrong.com/common}Comments" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="RequestType" type="{www.headstrong.com/common}RequestType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RefData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CobsId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Jurisdiction" type="{www.headstrong.com/common}Jurisdiction" minOccurs="0"/>
 *                   &lt;element name="CreatedDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="DueDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{www.headstrong.com/entity}Entity" minOccurs="0"/>
 *         &lt;element name="Risk" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OriginalRisk" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ReviewDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CalculatedRisk" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Score">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Product" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="OwnershipType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="BookingEntity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="FinalRisk">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="IsRiskOverriden" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="OverridenBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RaasID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemediationProfile", namespace = "www.headstrong.com", propOrder = {
    "profileStatusInfo",
    "refData",
    "entity",
    "risk"
})
public class RemediationProfile
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ProfileStatusInfo", required = true)
    protected RemediationProfile.ProfileStatusInfo profileStatusInfo;
    @XmlElement(name = "RefData", required = true)
    protected RemediationProfile.RefData refData;
    @XmlElement(name = "Entity", namespace = "www.headstrong.com/entity")
    protected Entity entity;
    @XmlElement(name = "Risk")
    protected RemediationProfile.Risk risk;
    @XmlAttribute(name = "LastUpdateDate")
    protected String lastUpdateDate;
    @XmlAttribute(name = "RaasID")
    protected String raasID;

    /**
     * Gets the value of the profileStatusInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RemediationProfile.ProfileStatusInfo }
     *     
     */
    public RemediationProfile.ProfileStatusInfo getProfileStatusInfo() {
        return profileStatusInfo;
    }

    /**
     * Sets the value of the profileStatusInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemediationProfile.ProfileStatusInfo }
     *     
     */
    public void setProfileStatusInfo(RemediationProfile.ProfileStatusInfo value) {
        this.profileStatusInfo = value;
    }

    /**
     * Gets the value of the refData property.
     * 
     * @return
     *     possible object is
     *     {@link RemediationProfile.RefData }
     *     
     */
    public RemediationProfile.RefData getRefData() {
        return refData;
    }

    /**
     * Sets the value of the refData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemediationProfile.RefData }
     *     
     */
    public void setRefData(RemediationProfile.RefData value) {
        this.refData = value;
    }

    /**
     * Gets the value of the entity property.
     * 
     * @return
     *     possible object is
     *     {@link Entity }
     *     
     */
    public Entity getEntity() {
        return entity;
    }

    /**
     * Sets the value of the entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entity }
     *     
     */
    public void setEntity(Entity value) {
        this.entity = value;
    }

    /**
     * Gets the value of the risk property.
     * 
     * @return
     *     possible object is
     *     {@link RemediationProfile.Risk }
     *     
     */
    public RemediationProfile.Risk getRisk() {
        return risk;
    }

    /**
     * Sets the value of the risk property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemediationProfile.Risk }
     *     
     */
    public void setRisk(RemediationProfile.Risk value) {
        this.risk = value;
    }

    /**
     * Gets the value of the lastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * Sets the value of the lastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateDate(String value) {
        this.lastUpdateDate = value;
    }

    /**
     * Gets the value of the raasID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaasID() {
        return raasID;
    }

    /**
     * Sets the value of the raasID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaasID(String value) {
        this.raasID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CurrentStatus">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Current_State" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Owner" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CaseNotes" type="{www.headstrong.com/common}Comments" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="RequestType" type="{www.headstrong.com/common}RequestType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currentStatus",
        "currentState",
        "caseNotes",
        "requestType"
    })
    public static class ProfileStatusInfo
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "CurrentStatus", required = true)
        protected RemediationProfile.ProfileStatusInfo.CurrentStatus currentStatus;
        @XmlElement(name = "Current_State", nillable = true)
        protected List<RemediationProfile.ProfileStatusInfo.CurrentState> currentState;
        @XmlElement(name = "CaseNotes")
        protected List<Comments> caseNotes;
        @XmlElement(name = "RequestType", required = true)
        protected RequestType requestType;

        /**
         * Gets the value of the currentStatus property.
         * 
         * @return
         *     possible object is
         *     {@link RemediationProfile.ProfileStatusInfo.CurrentStatus }
         *     
         */
        public RemediationProfile.ProfileStatusInfo.CurrentStatus getCurrentStatus() {
            return currentStatus;
        }

        /**
         * Sets the value of the currentStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link RemediationProfile.ProfileStatusInfo.CurrentStatus }
         *     
         */
        public void setCurrentStatus(RemediationProfile.ProfileStatusInfo.CurrentStatus value) {
            this.currentStatus = value;
        }

        /**
         * Gets the value of the currentState property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the currentState property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCurrentState().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RemediationProfile.ProfileStatusInfo.CurrentState }
         * 
         * 
         */
        public List<RemediationProfile.ProfileStatusInfo.CurrentState> getCurrentState() {
            if (currentState == null) {
                currentState = new ArrayList<RemediationProfile.ProfileStatusInfo.CurrentState>();
            }
            return this.currentState;
        }

        /**
         * Gets the value of the caseNotes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the caseNotes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCaseNotes().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Comments }
         * 
         * 
         */
        public List<Comments> getCaseNotes() {
            if (caseNotes == null) {
                caseNotes = new ArrayList<Comments>();
            }
            return this.caseNotes;
        }

        /**
         * Gets the value of the requestType property.
         * 
         * @return
         *     possible object is
         *     {@link RequestType }
         *     
         */
        public RequestType getRequestType() {
            return requestType;
        }

        /**
         * Sets the value of the requestType property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestType }
         *     
         */
        public void setRequestType(RequestType value) {
            this.requestType = value;
        }

        public void setCurrentState(List<RemediationProfile.ProfileStatusInfo.CurrentState> value) {
            this.currentState = value;
        }

        public void setCaseNotes(List<Comments> value) {
            this.caseNotes = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Owner" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CurrentState
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(name = "Owner")
            protected String owner;

            /**
             * Gets the value of the owner property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOwner() {
                return owner;
            }

            /**
             * Sets the value of the owner property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOwner(String value) {
                this.owner = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CurrentStatus
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(name = "LastUpdated")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar lastUpdated;

            /**
             * Gets the value of the lastUpdated property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getLastUpdated() {
                return lastUpdated;
            }

            /**
             * Sets the value of the lastUpdated property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setLastUpdated(XMLGregorianCalendar value) {
                this.lastUpdated = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CobsId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Jurisdiction" type="{www.headstrong.com/common}Jurisdiction" minOccurs="0"/>
     *         &lt;element name="CreatedDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="DueDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cobsId",
        "jurisdiction",
        "createdDT",
        "dueDT"
    })
    public static class RefData
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "CobsId", required = true)
        protected String cobsId;
        @XmlElement(name = "Jurisdiction")
        protected Jurisdiction jurisdiction;
        @XmlElement(name = "CreatedDT", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar createdDT;
        @XmlElement(name = "DueDT", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar dueDT;

        /**
         * Gets the value of the cobsId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCobsId() {
            return cobsId;
        }

        /**
         * Sets the value of the cobsId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCobsId(String value) {
            this.cobsId = value;
        }

        /**
         * Gets the value of the jurisdiction property.
         * 
         * @return
         *     possible object is
         *     {@link Jurisdiction }
         *     
         */
        public Jurisdiction getJurisdiction() {
            return jurisdiction;
        }

        /**
         * Sets the value of the jurisdiction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Jurisdiction }
         *     
         */
        public void setJurisdiction(Jurisdiction value) {
            this.jurisdiction = value;
        }

        /**
         * Gets the value of the createdDT property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreatedDT() {
            return createdDT;
        }

        /**
         * Sets the value of the createdDT property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreatedDT(XMLGregorianCalendar value) {
            this.createdDT = value;
        }

        /**
         * Gets the value of the dueDT property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDueDT() {
            return dueDT;
        }

        /**
         * Sets the value of the dueDT property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDueDT(XMLGregorianCalendar value) {
            this.dueDT = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OriginalRisk" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ReviewDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CalculatedRisk" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Score">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="Product" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="OwnershipType" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="BookingEntity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="FinalRisk">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IsRiskOverriden" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="OverridenBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originalRisk",
        "calculatedRisk",
        "finalRisk"
    })
    public static class Risk
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "OriginalRisk")
        protected RemediationProfile.Risk.OriginalRisk originalRisk;
        @XmlElement(name = "CalculatedRisk")
        protected RemediationProfile.Risk.CalculatedRisk calculatedRisk;
        @XmlElement(name = "FinalRisk", required = true)
        protected RemediationProfile.Risk.FinalRisk finalRisk;
        @XmlAttribute(name = "LastUpdated")
        protected String lastUpdated;

        /**
         * Gets the value of the originalRisk property.
         * 
         * @return
         *     possible object is
         *     {@link RemediationProfile.Risk.OriginalRisk }
         *     
         */
        public RemediationProfile.Risk.OriginalRisk getOriginalRisk() {
            return originalRisk;
        }

        /**
         * Sets the value of the originalRisk property.
         * 
         * @param value
         *     allowed object is
         *     {@link RemediationProfile.Risk.OriginalRisk }
         *     
         */
        public void setOriginalRisk(RemediationProfile.Risk.OriginalRisk value) {
            this.originalRisk = value;
        }

        /**
         * Gets the value of the calculatedRisk property.
         * 
         * @return
         *     possible object is
         *     {@link RemediationProfile.Risk.CalculatedRisk }
         *     
         */
        public RemediationProfile.Risk.CalculatedRisk getCalculatedRisk() {
            return calculatedRisk;
        }

        /**
         * Sets the value of the calculatedRisk property.
         * 
         * @param value
         *     allowed object is
         *     {@link RemediationProfile.Risk.CalculatedRisk }
         *     
         */
        public void setCalculatedRisk(RemediationProfile.Risk.CalculatedRisk value) {
            this.calculatedRisk = value;
        }

        /**
         * Gets the value of the finalRisk property.
         * 
         * @return
         *     possible object is
         *     {@link RemediationProfile.Risk.FinalRisk }
         *     
         */
        public RemediationProfile.Risk.FinalRisk getFinalRisk() {
            return finalRisk;
        }

        /**
         * Sets the value of the finalRisk property.
         * 
         * @param value
         *     allowed object is
         *     {@link RemediationProfile.Risk.FinalRisk }
         *     
         */
        public void setFinalRisk(RemediationProfile.Risk.FinalRisk value) {
            this.finalRisk = value;
        }

        /**
         * Gets the value of the lastUpdated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUpdated() {
            return lastUpdated;
        }

        /**
         * Sets the value of the lastUpdated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUpdated(String value) {
            this.lastUpdated = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Score">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="Product" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="OwnershipType" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="BookingEntity" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "score",
            "riskValue"
        })
        public static class CalculatedRisk
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "Score", required = true)
            protected RemediationProfile.Risk.CalculatedRisk.Score score;
            @XmlElement(name = "RiskValue", required = true)
            protected String riskValue;

            /**
             * Gets the value of the score property.
             * 
             * @return
             *     possible object is
             *     {@link RemediationProfile.Risk.CalculatedRisk.Score }
             *     
             */
            public RemediationProfile.Risk.CalculatedRisk.Score getScore() {
                return score;
            }

            /**
             * Sets the value of the score property.
             * 
             * @param value
             *     allowed object is
             *     {@link RemediationProfile.Risk.CalculatedRisk.Score }
             *     
             */
            public void setScore(RemediationProfile.Risk.CalculatedRisk.Score value) {
                this.score = value;
            }

            /**
             * Gets the value of the riskValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRiskValue() {
                return riskValue;
            }

            /**
             * Sets the value of the riskValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRiskValue(String value) {
                this.riskValue = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="Product" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="OwnershipType" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="BookingEntity" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "country",
                "product",
                "ownershipType",
                "bookingEntity"
            })
            public static class Score
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "Country")
                protected int country;
                @XmlElement(name = "Product")
                protected int product;
                @XmlElement(name = "OwnershipType")
                protected int ownershipType;
                @XmlElement(name = "BookingEntity")
                protected int bookingEntity;

                /**
                 * Gets the value of the country property.
                 * 
                 */
                public int getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 */
                public void setCountry(int value) {
                    this.country = value;
                }

                /**
                 * Gets the value of the product property.
                 * 
                 */
                public int getProduct() {
                    return product;
                }

                /**
                 * Sets the value of the product property.
                 * 
                 */
                public void setProduct(int value) {
                    this.product = value;
                }

                /**
                 * Gets the value of the ownershipType property.
                 * 
                 */
                public int getOwnershipType() {
                    return ownershipType;
                }

                /**
                 * Sets the value of the ownershipType property.
                 * 
                 */
                public void setOwnershipType(int value) {
                    this.ownershipType = value;
                }

                /**
                 * Gets the value of the bookingEntity property.
                 * 
                 */
                public int getBookingEntity() {
                    return bookingEntity;
                }

                /**
                 * Sets the value of the bookingEntity property.
                 * 
                 */
                public void setBookingEntity(int value) {
                    this.bookingEntity = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IsRiskOverriden" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="OverridenBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "isRiskOverriden",
            "riskValue",
            "overridenBy",
            "date",
            "reason",
            "comments"
        })
        public static class FinalRisk
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "IsRiskOverriden")
            protected boolean isRiskOverriden;
            @XmlElement(name = "RiskValue", required = true)
            protected String riskValue;
            @XmlElement(name = "OverridenBy", required = true)
            protected String overridenBy;
            @XmlElement(name = "Date", required = true)
            protected String date;
            @XmlElement(name = "Reason", required = true)
            protected String reason;
            @XmlElement(name = "Comments", required = true)
            protected String comments;

            /**
             * Gets the value of the isRiskOverriden property.
             * 
             */
            public boolean isIsRiskOverriden() {
                return isRiskOverriden;
            }

            /**
             * Sets the value of the isRiskOverriden property.
             * 
             */
            public void setIsRiskOverriden(boolean value) {
                this.isRiskOverriden = value;
            }

            /**
             * Gets the value of the riskValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRiskValue() {
                return riskValue;
            }

            /**
             * Sets the value of the riskValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRiskValue(String value) {
                this.riskValue = value;
            }

            /**
             * Gets the value of the overridenBy property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOverridenBy() {
                return overridenBy;
            }

            /**
             * Sets the value of the overridenBy property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOverridenBy(String value) {
                this.overridenBy = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

            /**
             * Gets the value of the reason property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReason() {
                return reason;
            }

            /**
             * Sets the value of the reason property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReason(String value) {
                this.reason = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RiskValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ReviewDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "riskValue",
            "reviewDate",
            "comments"
        })
        public static class OriginalRisk
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "RiskValue", required = true)
            protected String riskValue;
            @XmlElement(name = "ReviewDate", required = true)
            protected String reviewDate;
            @XmlElement(name = "Comments", required = true)
            protected String comments;

            /**
             * Gets the value of the riskValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRiskValue() {
                return riskValue;
            }

            /**
             * Sets the value of the riskValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRiskValue(String value) {
                this.riskValue = value;
            }

            /**
             * Gets the value of the reviewDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReviewDate() {
                return reviewDate;
            }

            /**
             * Sets the value of the reviewDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReviewDate(String value) {
                this.reviewDate = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

        }

    }

}
