//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SanctionCheckEventOrListType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SanctionCheckEventOrListType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Watch List"/>
 *     &lt;enumeration value="Associated With"/>
 *     &lt;enumeration value="On List"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SanctionCheckEventOrListType")
@XmlEnum
public enum SanctionCheckEventOrListType {

    @XmlEnumValue("Watch List")
    WATCH_LIST("Watch List"),
    @XmlEnumValue("Associated With")
    ASSOCIATED_WITH("Associated With"),
    @XmlEnumValue("On List")
    ON_LIST("On List");
    private final String value;

    SanctionCheckEventOrListType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SanctionCheckEventOrListType fromValue(String v) {
        for (SanctionCheckEventOrListType c: SanctionCheckEventOrListType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
