//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 12:19:25 PM IST 
//


package com.headstrong.npi.raas.xml.pojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxIdAvailable" type="{www.headstrong.com/common}Option" minOccurs="0"/>
 *         &lt;element name="TaxIdIssuingCountry" type="{www.headstrong.com/common}Country" minOccurs="0"/>
 *         &lt;element name="TaxIdType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxIdAppliedForDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxInfo", propOrder = {
    "taxIdAvailable",
    "taxIdIssuingCountry",
    "taxIdType",
    "taxId",
    "taxIdAppliedForDate"
})
public class TaxInfo
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TaxIdAvailable")
    protected Option taxIdAvailable;
    @XmlElement(name = "TaxIdIssuingCountry")
    protected Country taxIdIssuingCountry;
    @XmlElement(name = "TaxIdType")
    protected String taxIdType;
    @XmlElement(name = "TaxId")
    protected String taxId;
    @XmlElement(name = "TaxIdAppliedForDate")
    protected String taxIdAppliedForDate;

    /**
     * Gets the value of the taxIdAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link Option }
     *     
     */
    public Option getTaxIdAvailable() {
        return taxIdAvailable;
    }

    /**
     * Sets the value of the taxIdAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Option }
     *     
     */
    public void setTaxIdAvailable(Option value) {
        this.taxIdAvailable = value;
    }

    /**
     * Gets the value of the taxIdIssuingCountry property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getTaxIdIssuingCountry() {
        return taxIdIssuingCountry;
    }

    /**
     * Sets the value of the taxIdIssuingCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setTaxIdIssuingCountry(Country value) {
        this.taxIdIssuingCountry = value;
    }

    /**
     * Gets the value of the taxIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIdType() {
        return taxIdType;
    }

    /**
     * Sets the value of the taxIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIdType(String value) {
        this.taxIdType = value;
    }

    /**
     * Gets the value of the taxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxId() {
        return taxId;
    }

    /**
     * Sets the value of the taxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxId(String value) {
        this.taxId = value;
    }

    /**
     * Gets the value of the taxIdAppliedForDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIdAppliedForDate() {
        return taxIdAppliedForDate;
    }

    /**
     * Sets the value of the taxIdAppliedForDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIdAppliedForDate(String value) {
        this.taxIdAppliedForDate = value;
    }

}
