//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Attribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Attribute">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="exception" type="{http://www.markit.com}Exception" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://www.markit.com}Comment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="challengeComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="document" type="{http://www.markit.com}Document" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="audit" type="{http://www.markit.com}AuditRecord" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Attribute", propOrder = {
    "validFrom",
    "validTo",
    "exception",
    "comment",
    "challengeComment",
    "document",
    "audit"
})
@XmlSeeAlso({
    AttributeDictionaryGovernmentIssuedIDType.class,
    AttributeCompanyGovernmentOwnership.class,
    AttributeCompanyLicenseInfo.class,
    AttributeDictionaryCurrency.class,
    AttributeEntity.class,
    AttributeCompanyCountryOfBusiness.class,
    AttributeCompanyBusinessActivity.class,
    AttributeCompanyFinancialInfo.class,
    AttributeDictionaryOwnershipType.class,
    AttributeDouble.class,
    AttributeDictionaryIndustryCode.class,
    AttributeCompany.class,
    AttributeDictionaryRegulator.class,
    AttributeDate.class,
    AttributeCompanyRegulatedInfo.class,
    AttributeLong.class,
    AttributeDictionaryDesignation.class,
    AttributeDictionaryIndustryCodeType.class,
    AttributeCompanyRelatedParty.class,
    AttributeCompanyControllerDirector.class,
    AttributeCompanyEntityName.class,
    AttributeCompanyBearerShare.class,
    AttributeCompanyIndustryIdentifier.class,
    AttributeCompanyBeneficialOwner.class,
    AttributeDictionaryCountry.class,
    AttributeCompanyFormation.class,
    AttributeCompanyListedInfo.class,
    AttributeDictionaryExchange.class,
    AttributeDictionaryKeyFinancialIndicator.class,
    AttributeDictionaryBookingJurisdiction.class,
    AttributeCompanyGovernmentIDInfo.class,
    AttributeBoolean.class,
    AttributeString.class,
    AttributeIndividualGovernmentIDInfo.class,
    AttributeCompanyContact.class,
    AttributeEntityStructure.class,
    AttributeDictionaryState.class,
    AttributeCompanyAML.class,
    AttributeCompanyBusinessActivityIndustryCode.class,
    AttributeEntityType.class,
    AttributeAddress.class,
    AttributeDictionaryIndividualGovernmentIdType.class
})
public abstract class Attribute {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validFrom;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validTo;
    protected List<Exception> exception;
    protected List<Comment> comment;
    protected String challengeComment;
    protected List<Document> document;
    protected List<AuditRecord> audit;

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the exception property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exception property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Exception }
     * 
     * 
     */
    public List<Exception> getException() {
        if (exception == null) {
            exception = new ArrayList<Exception>();
        }
        return this.exception;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    public List<Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<Comment>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the challengeComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChallengeComment() {
        return challengeComment;
    }

    /**
     * Sets the value of the challengeComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChallengeComment(String value) {
        this.challengeComment = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Document }
     * 
     * 
     */
    public List<Document> getDocument() {
        if (document == null) {
            document = new ArrayList<Document>();
        }
        return this.document;
    }

    /**
     * Gets the value of the audit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuditRecord }
     * 
     * 
     */
    public List<AuditRecord> getAudit() {
        if (audit == null) {
            audit = new ArrayList<AuditRecord>();
        }
        return this.audit;
    }

    public void setException(List<Exception> value) {
        this.exception = value;
    }

    public void setComment(List<Comment> value) {
        this.comment = value;
    }

    public void setDocument(List<Document> value) {
        this.document = value;
    }

    public void setAudit(List<AuditRecord> value) {
        this.audit = value;
    }

}
