//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Case complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Case">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entityProfile" type="{http://www.markit.com}AttributeEntity"/>
 *         &lt;element name="bookingJurisdiction" type="{http://www.markit.com}DictionaryBookingJurisdiction" maxOccurs="unbounded"/>
 *         &lt;element name="createdDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="dueDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="responseStatus" type="{http://www.markit.com}CaseResponseStatus" minOccurs="0"/>
 *         &lt;element name="completedDT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Case", propOrder = {
    "caseId",
    "entityProfile",
    "bookingJurisdiction",
    "createdDT",
    "dueDT",
    "responseStatus",
    "completedDT"
})
@XmlSeeAlso({
    FullReviewCase.class,
    FormationCase.class,
    ChallengeCase.class
})
public abstract class Case {

    @XmlElement(required = true)
    protected String caseId;
    @XmlElement(required = true)
    protected AttributeEntity entityProfile;
    @XmlElement(required = true)
    protected List<DictionaryBookingJurisdiction> bookingJurisdiction;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDT;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dueDT;
    protected CaseResponseStatus responseStatus;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar completedDT;

    /**
     * Gets the value of the caseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * Sets the value of the caseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseId(String value) {
        this.caseId = value;
    }

    /**
     * Gets the value of the entityProfile property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeEntity }
     *     
     */
    public AttributeEntity getEntityProfile() {
        return entityProfile;
    }

    /**
     * Sets the value of the entityProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeEntity }
     *     
     */
    public void setEntityProfile(AttributeEntity value) {
        this.entityProfile = value;
    }

    /**
     * Gets the value of the bookingJurisdiction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bookingJurisdiction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBookingJurisdiction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DictionaryBookingJurisdiction }
     * 
     * 
     */
    public List<DictionaryBookingJurisdiction> getBookingJurisdiction() {
        if (bookingJurisdiction == null) {
            bookingJurisdiction = new ArrayList<DictionaryBookingJurisdiction>();
        }
        return this.bookingJurisdiction;
    }

    /**
     * Gets the value of the createdDT property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDT() {
        return createdDT;
    }

    /**
     * Sets the value of the createdDT property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDT(XMLGregorianCalendar value) {
        this.createdDT = value;
    }

    /**
     * Gets the value of the dueDT property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDT() {
        return dueDT;
    }

    /**
     * Sets the value of the dueDT property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDT(XMLGregorianCalendar value) {
        this.dueDT = value;
    }

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CaseResponseStatus }
     *     
     */
    public CaseResponseStatus getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseResponseStatus }
     *     
     */
    public void setResponseStatus(CaseResponseStatus value) {
        this.responseStatus = value;
    }

    /**
     * Gets the value of the completedDT property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCompletedDT() {
        return completedDT;
    }

    /**
     * Sets the value of the completedDT property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCompletedDT(XMLGregorianCalendar value) {
        this.completedDT = value;
    }

    public void setBookingJurisdiction(List<DictionaryBookingJurisdiction> value) {
        this.bookingJurisdiction = value;
    }

}
