//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * [A500] An indicator of whether the entity lists common share equities on a public stock exchange
 * 			
 * 
 * <p>Java class for CompanyListedInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyListedInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isPubliclyListed" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *         &lt;element name="primaryExchange" type="{http://www.markit.com}AttributeDictionaryExchange" minOccurs="0"/>
 *         &lt;element name="primaryExchangeTicker" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="isPrimaryExchangeApproved" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyListedInfo", propOrder = {
    "isPubliclyListed",
    "primaryExchange",
    "primaryExchangeTicker",
    "isPrimaryExchangeApproved"
})
public class CompanyListedInfo {

    protected AttributeBoolean isPubliclyListed;
    protected AttributeDictionaryExchange primaryExchange;
    protected AttributeString primaryExchangeTicker;
    protected AttributeBoolean isPrimaryExchangeApproved;

    /**
     * Gets the value of the isPubliclyListed property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getIsPubliclyListed() {
        return isPubliclyListed;
    }

    /**
     * Sets the value of the isPubliclyListed property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setIsPubliclyListed(AttributeBoolean value) {
        this.isPubliclyListed = value;
    }

    /**
     * Gets the value of the primaryExchange property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDictionaryExchange }
     *     
     */
    public AttributeDictionaryExchange getPrimaryExchange() {
        return primaryExchange;
    }

    /**
     * Sets the value of the primaryExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDictionaryExchange }
     *     
     */
    public void setPrimaryExchange(AttributeDictionaryExchange value) {
        this.primaryExchange = value;
    }

    /**
     * Gets the value of the primaryExchangeTicker property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getPrimaryExchangeTicker() {
        return primaryExchangeTicker;
    }

    /**
     * Sets the value of the primaryExchangeTicker property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setPrimaryExchangeTicker(AttributeString value) {
        this.primaryExchangeTicker = value;
    }

    /**
     * Gets the value of the isPrimaryExchangeApproved property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getIsPrimaryExchangeApproved() {
        return isPrimaryExchangeApproved;
    }

    /**
     * Sets the value of the isPrimaryExchangeApproved property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setIsPrimaryExchangeApproved(AttributeBoolean value) {
        this.isPrimaryExchangeApproved = value;
    }

}
