//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyEntityName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyEntityName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="previousLegalName" type="{http://www.markit.com}AttributeString"/>
 *         &lt;element name="previousLegalNameEndDate" type="{http://www.markit.com}AttributeDate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyEntityName", propOrder = {
    "previousLegalName",
    "previousLegalNameEndDate"
})
public class CompanyEntityName {

    @XmlElement(required = true)
    protected AttributeString previousLegalName;
    @XmlElement(required = true)
    protected AttributeDate previousLegalNameEndDate;

    /**
     * Gets the value of the previousLegalName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getPreviousLegalName() {
        return previousLegalName;
    }

    /**
     * Sets the value of the previousLegalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setPreviousLegalName(AttributeString value) {
        this.previousLegalName = value;
    }

    /**
     * Gets the value of the previousLegalNameEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDate }
     *     
     */
    public AttributeDate getPreviousLegalNameEndDate() {
        return previousLegalNameEndDate;
    }

    /**
     * Sets the value of the previousLegalNameEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDate }
     *     
     */
    public void setPreviousLegalNameEndDate(AttributeDate value) {
        this.previousLegalNameEndDate = value;
    }

}
