//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyBearerShare complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyBearerShare">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jurisdictionAllowsIssuance" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *         &lt;element name="articlesAllowIssuance" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *         &lt;element name="haveBeenIssued" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *         &lt;element name="percentageIssued" type="{http://www.markit.com}AttributeDouble" minOccurs="0"/>
 *         &lt;element name="heldInCustody" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *         &lt;element name="custodianName" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="ownershipStructureIssued" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyBearerShare", propOrder = {
    "jurisdictionAllowsIssuance",
    "articlesAllowIssuance",
    "haveBeenIssued",
    "percentageIssued",
    "heldInCustody",
    "custodianName",
    "ownershipStructureIssued"
})
public class CompanyBearerShare {

    protected AttributeBoolean jurisdictionAllowsIssuance;
    protected AttributeBoolean articlesAllowIssuance;
    protected AttributeBoolean haveBeenIssued;
    protected AttributeDouble percentageIssued;
    protected AttributeBoolean heldInCustody;
    protected AttributeString custodianName;
    protected AttributeBoolean ownershipStructureIssued;

    /**
     * Gets the value of the jurisdictionAllowsIssuance property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getJurisdictionAllowsIssuance() {
        return jurisdictionAllowsIssuance;
    }

    /**
     * Sets the value of the jurisdictionAllowsIssuance property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setJurisdictionAllowsIssuance(AttributeBoolean value) {
        this.jurisdictionAllowsIssuance = value;
    }

    /**
     * Gets the value of the articlesAllowIssuance property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getArticlesAllowIssuance() {
        return articlesAllowIssuance;
    }

    /**
     * Sets the value of the articlesAllowIssuance property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setArticlesAllowIssuance(AttributeBoolean value) {
        this.articlesAllowIssuance = value;
    }

    /**
     * Gets the value of the haveBeenIssued property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getHaveBeenIssued() {
        return haveBeenIssued;
    }

    /**
     * Sets the value of the haveBeenIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setHaveBeenIssued(AttributeBoolean value) {
        this.haveBeenIssued = value;
    }

    /**
     * Gets the value of the percentageIssued property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDouble }
     *     
     */
    public AttributeDouble getPercentageIssued() {
        return percentageIssued;
    }

    /**
     * Sets the value of the percentageIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDouble }
     *     
     */
    public void setPercentageIssued(AttributeDouble value) {
        this.percentageIssued = value;
    }

    /**
     * Gets the value of the heldInCustody property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getHeldInCustody() {
        return heldInCustody;
    }

    /**
     * Sets the value of the heldInCustody property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setHeldInCustody(AttributeBoolean value) {
        this.heldInCustody = value;
    }

    /**
     * Gets the value of the custodianName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getCustodianName() {
        return custodianName;
    }

    /**
     * Sets the value of the custodianName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setCustodianName(AttributeString value) {
        this.custodianName = value;
    }

    /**
     * Gets the value of the ownershipStructureIssued property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getOwnershipStructureIssued() {
        return ownershipStructureIssued;
    }

    /**
     * Sets the value of the ownershipStructureIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setOwnershipStructureIssued(AttributeBoolean value) {
        this.ownershipStructureIssued = value;
    }

}
