//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyContact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyContact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="role" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="position" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="phone" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="fax" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="individual" type="{http://www.markit.com}Individual" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyContact", propOrder = {
    "role",
    "position",
    "phone",
    "fax",
    "email",
    "individual"
})
public class CompanyContact {

    protected AttributeString role;
    protected AttributeString position;
    protected AttributeString phone;
    protected AttributeString fax;
    protected AttributeString email;
    protected Individual individual;

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setRole(AttributeString value) {
        this.role = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setPosition(AttributeString value) {
        this.position = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setPhone(AttributeString value) {
        this.phone = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setFax(AttributeString value) {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setEmail(AttributeString value) {
        this.email = value;
    }

    /**
     * Gets the value of the individual property.
     * 
     * @return
     *     possible object is
     *     {@link Individual }
     *     
     */
    public Individual getIndividual() {
        return individual;
    }

    /**
     * Sets the value of the individual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Individual }
     *     
     */
    public void setIndividual(Individual value) {
        this.individual = value;
    }

}
