//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyAML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyAML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="completedWolfsbergQuestionnaireProvided" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *         &lt;element name="signatureDateCompletedWolfsbergQuestionnaire" type="{http://www.markit.com}AttributeDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyAML", propOrder = {
    "completedWolfsbergQuestionnaireProvided",
    "signatureDateCompletedWolfsbergQuestionnaire"
})
public class CompanyAML {

    protected AttributeBoolean completedWolfsbergQuestionnaireProvided;
    protected AttributeDate signatureDateCompletedWolfsbergQuestionnaire;

    /**
     * Gets the value of the completedWolfsbergQuestionnaireProvided property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getCompletedWolfsbergQuestionnaireProvided() {
        return completedWolfsbergQuestionnaireProvided;
    }

    /**
     * Sets the value of the completedWolfsbergQuestionnaireProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setCompletedWolfsbergQuestionnaireProvided(AttributeBoolean value) {
        this.completedWolfsbergQuestionnaireProvided = value;
    }

    /**
     * Gets the value of the signatureDateCompletedWolfsbergQuestionnaire property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDate }
     *     
     */
    public AttributeDate getSignatureDateCompletedWolfsbergQuestionnaire() {
        return signatureDateCompletedWolfsbergQuestionnaire;
    }

    /**
     * Sets the value of the signatureDateCompletedWolfsbergQuestionnaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDate }
     *     
     */
    public void setSignatureDateCompletedWolfsbergQuestionnaire(AttributeDate value) {
        this.signatureDateCompletedWolfsbergQuestionnaire = value;
    }

}
