//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyBusinessActivityIndustryCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyBusinessActivityIndustryCode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="industryCode" type="{http://www.markit.com}AttributeString"/>
 *         &lt;element name="industryCodeType" type="{http://www.markit.com}AttributeDictionaryIndustryCodeType"/>
 *         &lt;element name="industryCodeDescription" type="{http://www.markit.com}AttributeString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyBusinessActivityIndustryCode", propOrder = {
    "industryCode",
    "industryCodeType",
    "industryCodeDescription"
})
public class CompanyBusinessActivityIndustryCode {

    @XmlElement(required = true)
    protected AttributeString industryCode;
    @XmlElement(required = true)
    protected AttributeDictionaryIndustryCodeType industryCodeType;
    @XmlElement(required = true)
    protected AttributeString industryCodeDescription;

    /**
     * Gets the value of the industryCode property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getIndustryCode() {
        return industryCode;
    }

    /**
     * Sets the value of the industryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setIndustryCode(AttributeString value) {
        this.industryCode = value;
    }

    /**
     * Gets the value of the industryCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDictionaryIndustryCodeType }
     *     
     */
    public AttributeDictionaryIndustryCodeType getIndustryCodeType() {
        return industryCodeType;
    }

    /**
     * Sets the value of the industryCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDictionaryIndustryCodeType }
     *     
     */
    public void setIndustryCodeType(AttributeDictionaryIndustryCodeType value) {
        this.industryCodeType = value;
    }

    /**
     * Gets the value of the industryCodeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getIndustryCodeDescription() {
        return industryCodeDescription;
    }

    /**
     * Sets the value of the industryCodeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setIndustryCodeDescription(AttributeString value) {
        this.industryCodeDescription = value;
    }

}
