//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyGovernmentOwnership complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyGovernmentOwnership">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="governmentEntityIdentified" type="{http://www.markit.com}AttributeBoolean" minOccurs="0"/>
 *         &lt;element name="governmentEntityName" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="governmentPercentage" type="{http://www.markit.com}AttributeDouble" minOccurs="0"/>
 *         &lt;element name="governmentCircumstances" type="{http://www.markit.com}AttributeString" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyGovernmentOwnership", propOrder = {
    "governmentEntityIdentified",
    "governmentEntityName",
    "governmentPercentage"
})
public class CompanyGovernmentOwnership {

    protected AttributeBoolean governmentEntityIdentified;
    protected AttributeString governmentEntityName;
    protected AttributeDouble governmentPercentage;

    /**
     * Gets the value of the governmentEntityIdentified property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getGovernmentEntityIdentified() {
        return governmentEntityIdentified;
    }

    /**
     * Sets the value of the governmentEntityIdentified property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setGovernmentEntityIdentified(AttributeBoolean value) {
        this.governmentEntityIdentified = value;
    }

    /**
     * Gets the value of the governmentEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getGovernmentEntityName() {
        return governmentEntityName;
    }

    /**
     * Sets the value of the governmentEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setGovernmentEntityName(AttributeString value) {
        this.governmentEntityName = value;
    }

    /**
     * Gets the value of the governmentPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDouble }
     *     
     */
    public AttributeDouble getGovernmentPercentage() {
        return governmentPercentage;
    }

    /**
     * Sets the value of the governmentPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDouble }
     *     
     */
    public void setGovernmentPercentage(AttributeDouble value) {
        this.governmentPercentage = value;
    }

}
