//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyBusinessActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyBusinessActivity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="natureOfBusiness" type="{http://www.markit.com}AttributeString"/>
 *         &lt;element name="numberOfEmployees" type="{http://www.markit.com}AttributeString"/>
 *         &lt;element name="economicSanctionedJurisdiction" type="{http://www.markit.com}AttributeBoolean"/>
 *         &lt;element name="revenueFromArmsDefense" type="{http://www.markit.com}AttributeBoolean"/>
 *         &lt;element name="revenueFromGambling" type="{http://www.markit.com}AttributeBoolean"/>
 *         &lt;element name="revenueFromMSB" type="{http://www.markit.com}AttributeBoolean"/>
 *         &lt;element name="revenueFromInternetGambling" type="{http://www.markit.com}AttributeBoolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyBusinessActivity", propOrder = {
    "natureOfBusiness",
    "numberOfEmployees",
    "economicSanctionedJurisdiction",
    "revenueFromArmsDefense",
    "revenueFromGambling",
    "revenueFromMSB",
    "revenueFromInternetGambling"
})
public class CompanyBusinessActivity {

    @XmlElement(required = true)
    protected AttributeString natureOfBusiness;
    @XmlElement(required = true)
    protected AttributeString numberOfEmployees;
    @XmlElement(required = true)
    protected AttributeBoolean economicSanctionedJurisdiction;
    @XmlElement(required = true)
    protected AttributeBoolean revenueFromArmsDefense;
    @XmlElement(required = true)
    protected AttributeBoolean revenueFromGambling;
    @XmlElement(required = true)
    protected AttributeBoolean revenueFromMSB;
    @XmlElement(required = true)
    protected AttributeBoolean revenueFromInternetGambling;

    /**
     * Gets the value of the natureOfBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getNatureOfBusiness() {
        return natureOfBusiness;
    }

    /**
     * Sets the value of the natureOfBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setNatureOfBusiness(AttributeString value) {
        this.natureOfBusiness = value;
    }

    /**
     * Gets the value of the numberOfEmployees property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getNumberOfEmployees() {
        return numberOfEmployees;
    }

    /**
     * Sets the value of the numberOfEmployees property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setNumberOfEmployees(AttributeString value) {
        this.numberOfEmployees = value;
    }

    /**
     * Gets the value of the economicSanctionedJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getEconomicSanctionedJurisdiction() {
        return economicSanctionedJurisdiction;
    }

    /**
     * Sets the value of the economicSanctionedJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setEconomicSanctionedJurisdiction(AttributeBoolean value) {
        this.economicSanctionedJurisdiction = value;
    }

    /**
     * Gets the value of the revenueFromArmsDefense property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getRevenueFromArmsDefense() {
        return revenueFromArmsDefense;
    }

    /**
     * Sets the value of the revenueFromArmsDefense property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setRevenueFromArmsDefense(AttributeBoolean value) {
        this.revenueFromArmsDefense = value;
    }

    /**
     * Gets the value of the revenueFromGambling property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getRevenueFromGambling() {
        return revenueFromGambling;
    }

    /**
     * Sets the value of the revenueFromGambling property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setRevenueFromGambling(AttributeBoolean value) {
        this.revenueFromGambling = value;
    }

    /**
     * Gets the value of the revenueFromMSB property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getRevenueFromMSB() {
        return revenueFromMSB;
    }

    /**
     * Sets the value of the revenueFromMSB property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setRevenueFromMSB(AttributeBoolean value) {
        this.revenueFromMSB = value;
    }

    /**
     * Gets the value of the revenueFromInternetGambling property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBoolean }
     *     
     */
    public AttributeBoolean getRevenueFromInternetGambling() {
        return revenueFromInternetGambling;
    }

    /**
     * Sets the value of the revenueFromInternetGambling property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBoolean }
     *     
     */
    public void setRevenueFromInternetGambling(AttributeBoolean value) {
        this.revenueFromInternetGambling = value;
    }

}
