//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyGovernmentIDInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyGovernmentIDInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idType" type="{http://www.markit.com}AttributeDictionaryGovernmentIssuedIDType" minOccurs="0"/>
 *         &lt;element name="idNumber" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="appliedForDate" type="{http://www.markit.com}AttributeDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyGovernmentIDInfo", propOrder = {
    "idType",
    "idNumber",
    "appliedForDate"
})
public class CompanyGovernmentIDInfo {

    protected AttributeDictionaryGovernmentIssuedIDType idType;
    protected AttributeString idNumber;
    protected AttributeDate appliedForDate;

    /**
     * Gets the value of the idType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDictionaryGovernmentIssuedIDType }
     *     
     */
    public AttributeDictionaryGovernmentIssuedIDType getIdType() {
        return idType;
    }

    /**
     * Sets the value of the idType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDictionaryGovernmentIssuedIDType }
     *     
     */
    public void setIdType(AttributeDictionaryGovernmentIssuedIDType value) {
        this.idType = value;
    }

    /**
     * Gets the value of the idNumber property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getIdNumber() {
        return idNumber;
    }

    /**
     * Sets the value of the idNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setIdNumber(AttributeString value) {
        this.idNumber = value;
    }

    /**
     * Gets the value of the appliedForDate property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDate }
     *     
     */
    public AttributeDate getAppliedForDate() {
        return appliedForDate;
    }

    /**
     * Sets the value of the appliedForDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDate }
     *     
     */
    public void setAppliedForDate(AttributeDate value) {
        this.appliedForDate = value;
    }

}
