//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DictionaryRegulator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DictionaryRegulator">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Australian Transaction Reports &amp; Analysis Centre (AUSTRAC)"/>
 *     &lt;enumeration value="Australian Prudential Regulation Authority (APRA)"/>
 *     &lt;enumeration value="Australian Securities and Investments Commission (ASIC) - Australian Financial Services Licenced (AFSL) entities only"/>
 *     &lt;enumeration value="Australian Securities and Investments Commission (ASIC)"/>
 *     &lt;enumeration value="Financial Market Authority (FMA)"/>
 *     &lt;enumeration value="�sterreische Nationalbank"/>
 *     &lt;enumeration value="Euronext"/>
 *     &lt;enumeration value="National Bank of Belgium"/>
 *     &lt;enumeration value="Financial Services and Markets Authority"/>
 *     &lt;enumeration value="Commission Bancaire, Financiere et des Assurances (CBFA)"/>
 *     &lt;enumeration value="Banco Central do Brasil"/>
 *     &lt;enumeration value="Comiss�o de Valores Mobili�rios (CVM)"/>
 *     &lt;enumeration value="Superintendencia de Seguros Privados (SUSEP)"/>
 *     &lt;enumeration value="The British Virgin Islands Financial Services Commission"/>
 *     &lt;enumeration value="Alberta Securities Commission"/>
 *     &lt;enumeration value="Autorit� des March�s Financiers (Quebec)"/>
 *     &lt;enumeration value="British Columbia Securities Commission"/>
 *     &lt;enumeration value="Canada Deposit Insurance Corporation"/>
 *     &lt;enumeration value="Financial Institutions Commission (British Columbia)"/>
 *     &lt;enumeration value="Financial Services Commission of Ontario (FSCO)"/>
 *     &lt;enumeration value="Investment Industry Regulatory Organization of Canada (IIROC)"/>
 *     &lt;enumeration value="Manitoba Securities Commission"/>
 *     &lt;enumeration value="Manitoba Superintendent of Financial Institutions"/>
 *     &lt;enumeration value="New Brunswick Securities Commission"/>
 *     &lt;enumeration value="New Brunswick Superintendent of Insurance"/>
 *     &lt;enumeration value="Newfoundland and Labrador Department of Government Services"/>
 *     &lt;enumeration value="Northwest Territories and Nunavut Superintendent of Insurance"/>
 *     &lt;enumeration value="Northwest Territories Superintendent/Registrar of Securities"/>
 *     &lt;enumeration value="Nova Scotia Securities Commission"/>
 *     &lt;enumeration value="Nova Scotia Superintendent of Insurance, Credit Unions and Trust and Loan Companies"/>
 *     &lt;enumeration value="Nunavut Superintendent/Registrar of Securities"/>
 *     &lt;enumeration value="Office of the Superintendent of Financial Institutions  (OSFI)"/>
 *     &lt;enumeration value="Ontario Securities Commission"/>
 *     &lt;enumeration value="Prince Edward Island Securities Office"/>
 *     &lt;enumeration value="Prince Edward Island Superintendent of Insurance"/>
 *     &lt;enumeration value="Provincial Securities Regulators"/>
 *     &lt;enumeration value="Saskatchewan Financial Services Commission"/>
 *     &lt;enumeration value="Securities Commission of Newfoundland and Labrador"/>
 *     &lt;enumeration value="Superintendent, Insurance and Financial Institutions (Alberta)"/>
 *     &lt;enumeration value="Yukon Superintendent/Registrar of Securities"/>
 *     &lt;enumeration value="Yukon Territory Superintendent of Insurance"/>
 *     &lt;enumeration value="Cayman Islands Monetary Authority"/>
 *     &lt;enumeration value="Ministry of Finance"/>
 *     &lt;enumeration value="Czech National Bank"/>
 *     &lt;enumeration value="Finanstilsynet (Danish Financial Supervisory Authority)"/>
 *     &lt;enumeration value="Bank of Estonia"/>
 *     &lt;enumeration value="Estonian Financial Supervision Authority"/>
 *     &lt;enumeration value="Finanssivalvonta Finansinspektionen (Financial Supervisory Authority)"/>
 *     &lt;enumeration value="Insurance Supervisory Authority"/>
 *     &lt;enumeration value="Autorit� de contr�le des assurances et des mutuelles"/>
 *     &lt;enumeration value="Autorit� de Controle Prudentiel (ACP)"/>
 *     &lt;enumeration value="Autorit� des March�s Financiers (AMF)"/>
 *     &lt;enumeration value="Banque de France"/>
 *     &lt;enumeration value="Commission Bancaire"/>
 *     &lt;enumeration value="Commission de Controle des Assurances, des mutuelles et de institutions de prevoyance"/>
 *     &lt;enumeration value="Ministere de l'Economie/Comite des Entreprises d'Assurances"/>
 *     &lt;enumeration value="Deutsche Bundesbank"/>
 *     &lt;enumeration value="Bundesanstalt fuer Finanzdienstleistungsaufsicht (BAFIN) (Federal Financial Supervisory Authority)"/>
 *     &lt;enumeration value="Financial Services Commission (FSC)"/>
 *     &lt;enumeration value="Bank of Greece"/>
 *     &lt;enumeration value="Hellenic Capital Market Commission"/>
 *     &lt;enumeration value="Ministry of Development, General Secretariat of Commerce Directorate of Insurance Enterprises &amp; Actuaries"/>
 *     &lt;enumeration value="Private Insurance Supervision Commission (PISC)"/>
 *     &lt;enumeration value="Financial Services Commission"/>
 *     &lt;enumeration value="Hong Kong Monetary Authority (HKMA)"/>
 *     &lt;enumeration value="Office of the Commissioner of Insurance"/>
 *     &lt;enumeration value="Securities and Futures Commission (SFC)"/>
 *     &lt;enumeration value="Financial Supervisory Authority"/>
 *     &lt;enumeration value="Fj�rmalaeftirlitid (Financial Supervisory Authority)"/>
 *     &lt;enumeration value="Reserve Bank of India"/>
 *     &lt;enumeration value="Security and Exchange Board of India (SEBI)"/>
 *     &lt;enumeration value="Insurance Regulatory Development Authority (IRDA)"/>
 *     &lt;enumeration value="Central Bank of Ireland"/>
 *     &lt;enumeration value="Irish Financial Services Regulatory Authority"/>
 *     &lt;enumeration value="Financial Supervision Commission (FSC)"/>
 *     &lt;enumeration value="Isle of Man Govt., Insurance &amp; Pensions Authority"/>
 *     &lt;enumeration value="Banca D'Italia"/>
 *     &lt;enumeration value="Commissione Nazionale per le Societa e le Borsa (CONSOB)"/>
 *     &lt;enumeration value="COVIP - Commissione di Vigilanza sui Fondi Pensione"/>
 *     &lt;enumeration value="Istituto per la Vigilanza sulle Assicurazioni Private e di Interesse Collettivo (ISVAP)"/>
 *     &lt;enumeration value="Financial Services Agency"/>
 *     &lt;enumeration value="Securities and Exchange Surveillance Commission"/>
 *     &lt;enumeration value="Financial Services Commission"/>
 *     &lt;enumeration value="Commissariat aux Assurances"/>
 *     &lt;enumeration value="Commission de Surveillance du Secteur Financier (CSSF)"/>
 *     &lt;enumeration value="Bank Negara Malaysia (Central Bank of Malaysia)"/>
 *     &lt;enumeration value="Securities Commission (Suruhanjaya Sekuriti)"/>
 *     &lt;enumeration value="Autoriteit Financi�le Markten (AFM) (Netherlands Authority for the Financial Markets)"/>
 *     &lt;enumeration value="De Nederlandsche Bank"/>
 *     &lt;enumeration value="Pensioen &amp; Verzekeringskamer"/>
 *     &lt;enumeration value="Ministry of Economic Development"/>
 *     &lt;enumeration value="Reserve Bank of New Zealand"/>
 *     &lt;enumeration value="Securities Commission"/>
 *     &lt;enumeration value="Insurance and Superannuation Unit (ISU)"/>
 *     &lt;enumeration value="Financial service providers"/>
 *     &lt;enumeration value="Finanstilsynet (formerly Kredittilsynet) (Financial Supervisory Authority)"/>
 *     &lt;enumeration value="Narodowy Bank Polski (National Bank of Poland)"/>
 *     &lt;enumeration value="Polish Financial Supervision Authority"/>
 *     &lt;enumeration value="The Polish Securities and Exchange Commission (Komisja Papier�w Warto\u015bciowych i Gie\u0142d)"/>
 *     &lt;enumeration value="Banco de Portugal"/>
 *     &lt;enumeration value="Comiss�o do Mercado de Valores Mobili�rios (CMVM) (Portuguese Securities Market Commission)"/>
 *     &lt;enumeration value="Instituto de Seguros de Portugal (Portuguese Insurance Institute)"/>
 *     &lt;enumeration value="National Bank Of Romania"/>
 *     &lt;enumeration value="Insurance Supervisory Commission"/>
 *     &lt;enumeration value="Romanian National Securities Commission"/>
 *     &lt;enumeration value="Monetary Authority of Singapore (MAS)"/>
 *     &lt;enumeration value="National Bank of Slovakia"/>
 *     &lt;enumeration value="Bank of Slovenia"/>
 *     &lt;enumeration value="Insurance Supervision Agency"/>
 *     &lt;enumeration value="Securities Market Agency"/>
 *     &lt;enumeration value="South African Reserve Bank"/>
 *     &lt;enumeration value="Financial Services Board"/>
 *     &lt;enumeration value="Financial Services Commission"/>
 *     &lt;enumeration value="Financial Supervisory Commission / Financial Supervisory Service"/>
 *     &lt;enumeration value="Banco de Espa�a"/>
 *     &lt;enumeration value="Comisi�n Nacional del Mercado de Valores (CNMV)"/>
 *     &lt;enumeration value="General Directorate of Insurance and Pension Funds (Direcci�n General de Seguros y Fondos de Pensiones)"/>
 *     &lt;enumeration value="Finansinspektionen (Swedish Financial Supervisory Authority)"/>
 *     &lt;enumeration value="Financial Market Supervisory Authority (FINMA)"/>
 *     &lt;enumeration value="Bundesamt f�r Privatversicherungen (BPV) (Federal Office of Private Insurance)"/>
 *     &lt;enumeration value="Eidgenoessische Finanzmarktaufsicht (Swiss Federal Banking Commission)"/>
 *     &lt;enumeration value="Eidgenoessische Finanzmarktaufsicht (Swiss Federal Banking Commission)"/>
 *     &lt;enumeration value="Financial Conduct Authority (FCA)"/>
 *     &lt;enumeration value="Prudential Regulation Authority (PRA) (Now FCA)"/>
 *     &lt;enumeration value="Financial Services Authority (FSA)"/>
 *     &lt;enumeration value="The Pensions Regulator"/>
 *     &lt;enumeration value="Board of Directors of the Federal Deposit Insurance Corporation (FDIC)"/>
 *     &lt;enumeration value="Commodity Futures Trading Commission (CFTC)"/>
 *     &lt;enumeration value="Federal Deposit Insurance Corporation (FDIC)"/>
 *     &lt;enumeration value="Federal Housing Finance Board"/>
 *     &lt;enumeration value="Federal Reserve System (FED)"/>
 *     &lt;enumeration value="Financial Industry Regulatory Authority (FINRA)"/>
 *     &lt;enumeration value="Florida Office of Financial Regulation"/>
 *     &lt;enumeration value="Municipal Securities Rulemarking Board"/>
 *     &lt;enumeration value="National Association of Insurance Commissioners (NAIC)"/>
 *     &lt;enumeration value="National Credit Union Administration (NCUA)"/>
 *     &lt;enumeration value="National Futures Association (NFA)"/>
 *     &lt;enumeration value="New York Department of Insurance"/>
 *     &lt;enumeration value="New York State Banking Department"/>
 *     &lt;enumeration value="Office of the Comptroller of the Currency (OCC)  / (OTS)"/>
 *     &lt;enumeration value="Securities and Exchange Commission (SEC)"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DictionaryRegulator")
@XmlEnum
public enum DictionaryRegulator {

    @XmlEnumValue("Australian Transaction Reports & Analysis Centre (AUSTRAC)")
    AUSTRALIAN_TRANSACTION_REPORTS_ANALYSIS_CENTRE_AUSTRAC("Australian Transaction Reports & Analysis Centre (AUSTRAC)"),
    @XmlEnumValue("Australian Prudential Regulation Authority (APRA)")
    AUSTRALIAN_PRUDENTIAL_REGULATION_AUTHORITY_APRA("Australian Prudential Regulation Authority (APRA)"),
    @XmlEnumValue("Australian Securities and Investments Commission (ASIC) - Australian Financial Services Licenced (AFSL) entities only")
    AUSTRALIAN_SECURITIES_AND_INVESTMENTS_COMMISSION_ASIC_AUSTRALIAN_FINANCIAL_SERVICES_LICENCED_AFSL_ENTITIES_ONLY("Australian Securities and Investments Commission (ASIC) - Australian Financial Services Licenced (AFSL) entities only"),
    @XmlEnumValue("Australian Securities and Investments Commission (ASIC)")
    AUSTRALIAN_SECURITIES_AND_INVESTMENTS_COMMISSION_ASIC("Australian Securities and Investments Commission (ASIC)"),
    @XmlEnumValue("Financial Market Authority (FMA)")
    FINANCIAL_MARKET_AUTHORITY_FMA("Financial Market Authority (FMA)"),
    @XmlEnumValue("\u00d6sterreische Nationalbank")
    STERREISCHE_NATIONALBANK("\u00d6sterreische Nationalbank"),
    @XmlEnumValue("Euronext")
    EURONEXT("Euronext"),
    @XmlEnumValue("National Bank of Belgium")
    NATIONAL_BANK_OF_BELGIUM("National Bank of Belgium"),
    @XmlEnumValue("Financial Services and Markets Authority")
    FINANCIAL_SERVICES_AND_MARKETS_AUTHORITY("Financial Services and Markets Authority"),
    @XmlEnumValue("Commission Bancaire, Financiere et des Assurances (CBFA)")
    COMMISSION_BANCAIRE_FINANCIERE_ET_DES_ASSURANCES_CBFA("Commission Bancaire, Financiere et des Assurances (CBFA)"),
    @XmlEnumValue("Banco Central do Brasil")
    BANCO_CENTRAL_DO_BRASIL("Banco Central do Brasil"),
    @XmlEnumValue("Comiss\u00e3o de Valores Mobili\u00e1rios (CVM)")
    COMISS_O_DE_VALORES_MOBILI_RIOS_CVM("Comiss\u00e3o de Valores Mobili\u00e1rios (CVM)"),
    @XmlEnumValue("Superintendencia de Seguros Privados (SUSEP)")
    SUPERINTENDENCIA_DE_SEGUROS_PRIVADOS_SUSEP("Superintendencia de Seguros Privados (SUSEP)"),
    @XmlEnumValue("The British Virgin Islands Financial Services Commission")
    THE_BRITISH_VIRGIN_ISLANDS_FINANCIAL_SERVICES_COMMISSION("The British Virgin Islands Financial Services Commission"),
    @XmlEnumValue("Alberta Securities Commission")
    ALBERTA_SECURITIES_COMMISSION("Alberta Securities Commission"),
    @XmlEnumValue("Autorit\u00e9 des March\u00e9s Financiers (Quebec)")
    AUTORIT_DES_MARCHS_FINANCIERS_QUEBEC("Autorit\u00e9 des March\u00e9s Financiers (Quebec)"),
    @XmlEnumValue("British Columbia Securities Commission")
    BRITISH_COLUMBIA_SECURITIES_COMMISSION("British Columbia Securities Commission"),
    @XmlEnumValue("Canada Deposit Insurance Corporation")
    CANADA_DEPOSIT_INSURANCE_CORPORATION("Canada Deposit Insurance Corporation"),
    @XmlEnumValue("Financial Institutions Commission (British Columbia)")
    FINANCIAL_INSTITUTIONS_COMMISSION_BRITISH_COLUMBIA("Financial Institutions Commission (British Columbia)"),
    @XmlEnumValue("Financial Services Commission of Ontario (FSCO)")
    FINANCIAL_SERVICES_COMMISSION_OF_ONTARIO_FSCO("Financial Services Commission of Ontario (FSCO)"),
    @XmlEnumValue("Investment Industry Regulatory Organization of Canada (IIROC)")
    INVESTMENT_INDUSTRY_REGULATORY_ORGANIZATION_OF_CANADA_IIROC("Investment Industry Regulatory Organization of Canada (IIROC)"),
    @XmlEnumValue("Manitoba Securities Commission")
    MANITOBA_SECURITIES_COMMISSION("Manitoba Securities Commission"),
    @XmlEnumValue("Manitoba Superintendent of Financial Institutions")
    MANITOBA_SUPERINTENDENT_OF_FINANCIAL_INSTITUTIONS("Manitoba Superintendent of Financial Institutions"),
    @XmlEnumValue("New Brunswick Securities Commission")
    NEW_BRUNSWICK_SECURITIES_COMMISSION("New Brunswick Securities Commission"),
    @XmlEnumValue("New Brunswick Superintendent of Insurance")
    NEW_BRUNSWICK_SUPERINTENDENT_OF_INSURANCE("New Brunswick Superintendent of Insurance"),
    @XmlEnumValue("Newfoundland and Labrador Department of Government Services")
    NEWFOUNDLAND_AND_LABRADOR_DEPARTMENT_OF_GOVERNMENT_SERVICES("Newfoundland and Labrador Department of Government Services"),
    @XmlEnumValue("Northwest Territories and Nunavut Superintendent of Insurance")
    NORTHWEST_TERRITORIES_AND_NUNAVUT_SUPERINTENDENT_OF_INSURANCE("Northwest Territories and Nunavut Superintendent of Insurance"),
    @XmlEnumValue("Northwest Territories Superintendent/Registrar of Securities")
    NORTHWEST_TERRITORIES_SUPERINTENDENT_REGISTRAR_OF_SECURITIES("Northwest Territories Superintendent/Registrar of Securities"),
    @XmlEnumValue("Nova Scotia Securities Commission")
    NOVA_SCOTIA_SECURITIES_COMMISSION("Nova Scotia Securities Commission"),
    @XmlEnumValue("Nova Scotia Superintendent of Insurance, Credit Unions and Trust and Loan Companies")
    NOVA_SCOTIA_SUPERINTENDENT_OF_INSURANCE_CREDIT_UNIONS_AND_TRUST_AND_LOAN_COMPANIES("Nova Scotia Superintendent of Insurance, Credit Unions and Trust and Loan Companies"),
    @XmlEnumValue("Nunavut Superintendent/Registrar of Securities")
    NUNAVUT_SUPERINTENDENT_REGISTRAR_OF_SECURITIES("Nunavut Superintendent/Registrar of Securities"),
    @XmlEnumValue("Office of the Superintendent of Financial Institutions  (OSFI)")
    OFFICE_OF_THE_SUPERINTENDENT_OF_FINANCIAL_INSTITUTIONS_OSFI("Office of the Superintendent of Financial Institutions  (OSFI)"),
    @XmlEnumValue("Ontario Securities Commission")
    ONTARIO_SECURITIES_COMMISSION("Ontario Securities Commission"),
    @XmlEnumValue("Prince Edward Island Securities Office")
    PRINCE_EDWARD_ISLAND_SECURITIES_OFFICE("Prince Edward Island Securities Office"),
    @XmlEnumValue("Prince Edward Island Superintendent of Insurance")
    PRINCE_EDWARD_ISLAND_SUPERINTENDENT_OF_INSURANCE("Prince Edward Island Superintendent of Insurance"),
    @XmlEnumValue("Provincial Securities Regulators")
    PROVINCIAL_SECURITIES_REGULATORS("Provincial Securities Regulators"),
    @XmlEnumValue("Saskatchewan Financial Services Commission")
    SASKATCHEWAN_FINANCIAL_SERVICES_COMMISSION("Saskatchewan Financial Services Commission"),
    @XmlEnumValue("Securities Commission of Newfoundland and Labrador")
    SECURITIES_COMMISSION_OF_NEWFOUNDLAND_AND_LABRADOR("Securities Commission of Newfoundland and Labrador"),
    @XmlEnumValue("Superintendent, Insurance and Financial Institutions (Alberta)")
    SUPERINTENDENT_INSURANCE_AND_FINANCIAL_INSTITUTIONS_ALBERTA("Superintendent, Insurance and Financial Institutions (Alberta)"),
    @XmlEnumValue("Yukon Superintendent/Registrar of Securities")
    YUKON_SUPERINTENDENT_REGISTRAR_OF_SECURITIES("Yukon Superintendent/Registrar of Securities"),
    @XmlEnumValue("Yukon Territory Superintendent of Insurance")
    YUKON_TERRITORY_SUPERINTENDENT_OF_INSURANCE("Yukon Territory Superintendent of Insurance"),
    @XmlEnumValue("Cayman Islands Monetary Authority")
    CAYMAN_ISLANDS_MONETARY_AUTHORITY("Cayman Islands Monetary Authority"),
    @XmlEnumValue("Ministry of Finance")
    MINISTRY_OF_FINANCE("Ministry of Finance"),
    @XmlEnumValue("Czech National Bank")
    CZECH_NATIONAL_BANK("Czech National Bank"),
    @XmlEnumValue("Finanstilsynet (Danish Financial Supervisory Authority)")
    FINANSTILSYNET_DANISH_FINANCIAL_SUPERVISORY_AUTHORITY("Finanstilsynet (Danish Financial Supervisory Authority)"),
    @XmlEnumValue("Bank of Estonia")
    BANK_OF_ESTONIA("Bank of Estonia"),
    @XmlEnumValue("Estonian Financial Supervision Authority")
    ESTONIAN_FINANCIAL_SUPERVISION_AUTHORITY("Estonian Financial Supervision Authority"),
    @XmlEnumValue("Finanssivalvonta Finansinspektionen (Financial Supervisory Authority)")
    FINANSSIVALVONTA_FINANSINSPEKTIONEN_FINANCIAL_SUPERVISORY_AUTHORITY("Finanssivalvonta Finansinspektionen (Financial Supervisory Authority)"),
    @XmlEnumValue("Insurance Supervisory Authority")
    INSURANCE_SUPERVISORY_AUTHORITY("Insurance Supervisory Authority"),
    @XmlEnumValue("Autorit\u00e9 de contr\u00f4le des assurances et des mutuelles")
    AUTORIT_DE_CONTR_LE_DES_ASSURANCES_ET_DES_MUTUELLES("Autorit\u00e9 de contr\u00f4le des assurances et des mutuelles"),
    @XmlEnumValue("Autorit\u00e9 de Controle Prudentiel (ACP)")
    AUTORIT_DE_CONTROLE_PRUDENTIEL_ACP("Autorit\u00e9 de Controle Prudentiel (ACP)"),
    @XmlEnumValue("Autorit\u00e9 des March\u00e9s Financiers (AMF)")
    AUTORIT_DES_MARCH_S_FINANCIERS_AMF("Autorit\u00e9 des March\u00e9s Financiers (AMF)"),
    @XmlEnumValue("Banque de France")
    BANQUE_DE_FRANCE("Banque de France"),
    @XmlEnumValue("Commission Bancaire")
    COMMISSION_BANCAIRE("Commission Bancaire"),
    @XmlEnumValue("Commission de Controle des Assurances, des mutuelles et de institutions de prevoyance")
    COMMISSION_DE_CONTROLE_DES_ASSURANCES_DES_MUTUELLES_ET_DE_INSTITUTIONS_DE_PREVOYANCE("Commission de Controle des Assurances, des mutuelles et de institutions de prevoyance"),
    @XmlEnumValue("Ministere de l'Economie/Comite des Entreprises d'Assurances")
    MINISTERE_DE_L_ECONOMIE_COMITE_DES_ENTREPRISES_D_ASSURANCES("Ministere de l'Economie/Comite des Entreprises d'Assurances"),
    @XmlEnumValue("Deutsche Bundesbank")
    DEUTSCHE_BUNDESBANK("Deutsche Bundesbank"),
    @XmlEnumValue("Bundesanstalt fuer Finanzdienstleistungsaufsicht (BAFIN) (Federal Financial Supervisory Authority)")
    BUNDESANSTALT_FUER_FINANZDIENSTLEISTUNGSAUFSICHT_BAFIN_FEDERAL_FINANCIAL_SUPERVISORY_AUTHORITY("Bundesanstalt fuer Finanzdienstleistungsaufsicht (BAFIN) (Federal Financial Supervisory Authority)"),
    @XmlEnumValue("Financial Services Commission (FSC)")
    FINANCIAL_SERVICES_COMMISSION_FSC("Financial Services Commission (FSC)"),
    @XmlEnumValue("Bank of Greece")
    BANK_OF_GREECE("Bank of Greece"),
    @XmlEnumValue("Hellenic Capital Market Commission")
    HELLENIC_CAPITAL_MARKET_COMMISSION("Hellenic Capital Market Commission"),
    @XmlEnumValue("Ministry of Development, General Secretariat of Commerce Directorate of Insurance Enterprises & Actuaries")
    MINISTRY_OF_DEVELOPMENT_GENERAL_SECRETARIAT_OF_COMMERCE_DIRECTORATE_OF_INSURANCE_ENTERPRISES_ACTUARIES("Ministry of Development, General Secretariat of Commerce Directorate of Insurance Enterprises & Actuaries"),
    @XmlEnumValue("Private Insurance Supervision Commission (PISC)")
    PRIVATE_INSURANCE_SUPERVISION_COMMISSION_PISC("Private Insurance Supervision Commission (PISC)"),
    @XmlEnumValue("Financial Services Commission")
    FINANCIAL_SERVICES_COMMISSION("Financial Services Commission"),
    @XmlEnumValue("Hong Kong Monetary Authority (HKMA)")
    HONG_KONG_MONETARY_AUTHORITY_HKMA("Hong Kong Monetary Authority (HKMA)"),
    @XmlEnumValue("Office of the Commissioner of Insurance")
    OFFICE_OF_THE_COMMISSIONER_OF_INSURANCE("Office of the Commissioner of Insurance"),
    @XmlEnumValue("Securities and Futures Commission (SFC)")
    SECURITIES_AND_FUTURES_COMMISSION_SFC("Securities and Futures Commission (SFC)"),
    @XmlEnumValue("Financial Supervisory Authority")
    FINANCIAL_SUPERVISORY_AUTHORITY("Financial Supervisory Authority"),
    @XmlEnumValue("Fj\u00e1rmalaeftirlitid (Financial Supervisory Authority)")
    FJ_RMALAEFTIRLITID_FINANCIAL_SUPERVISORY_AUTHORITY("Fj\u00e1rmalaeftirlitid (Financial Supervisory Authority)"),
    @XmlEnumValue("Reserve Bank of India")
    RESERVE_BANK_OF_INDIA("Reserve Bank of India"),
    @XmlEnumValue("Security and Exchange Board of India (SEBI)")
    SECURITY_AND_EXCHANGE_BOARD_OF_INDIA_SEBI("Security and Exchange Board of India (SEBI)"),
    @XmlEnumValue("Insurance Regulatory Development Authority (IRDA)")
    INSURANCE_REGULATORY_DEVELOPMENT_AUTHORITY_IRDA("Insurance Regulatory Development Authority (IRDA)"),
    @XmlEnumValue("Central Bank of Ireland")
    CENTRAL_BANK_OF_IRELAND("Central Bank of Ireland"),
    @XmlEnumValue("Irish Financial Services Regulatory Authority")
    IRISH_FINANCIAL_SERVICES_REGULATORY_AUTHORITY("Irish Financial Services Regulatory Authority"),
    @XmlEnumValue("Financial Supervision Commission (FSC)")
    FINANCIAL_SUPERVISION_COMMISSION_FSC("Financial Supervision Commission (FSC)"),
    @XmlEnumValue("Isle of Man Govt., Insurance & Pensions Authority")
    ISLE_OF_MAN_GOVT_INSURANCE_PENSIONS_AUTHORITY("Isle of Man Govt., Insurance & Pensions Authority"),
    @XmlEnumValue("Banca D'Italia")
    BANCA_D_ITALIA("Banca D'Italia"),
    @XmlEnumValue("Commissione Nazionale per le Societa e le Borsa (CONSOB)")
    COMMISSIONE_NAZIONALE_PER_LE_SOCIETA_E_LE_BORSA_CONSOB("Commissione Nazionale per le Societa e le Borsa (CONSOB)"),
    @XmlEnumValue("COVIP - Commissione di Vigilanza sui Fondi Pensione")
    COVIP_COMMISSIONE_DI_VIGILANZA_SUI_FONDI_PENSIONE("COVIP - Commissione di Vigilanza sui Fondi Pensione"),
    @XmlEnumValue("Istituto per la Vigilanza sulle Assicurazioni Private e di Interesse Collettivo (ISVAP)")
    ISTITUTO_PER_LA_VIGILANZA_SULLE_ASSICURAZIONI_PRIVATE_E_DI_INTERESSE_COLLETTIVO_ISVAP("Istituto per la Vigilanza sulle Assicurazioni Private e di Interesse Collettivo (ISVAP)"),
    @XmlEnumValue("Financial Services Agency")
    FINANCIAL_SERVICES_AGENCY("Financial Services Agency"),
    @XmlEnumValue("Securities and Exchange Surveillance Commission")
    SECURITIES_AND_EXCHANGE_SURVEILLANCE_COMMISSION("Securities and Exchange Surveillance Commission"),
    @XmlEnumValue("Commissariat aux Assurances")
    COMMISSARIAT_AUX_ASSURANCES("Commissariat aux Assurances"),
    @XmlEnumValue("Commission de Surveillance du Secteur Financier (CSSF)")
    COMMISSION_DE_SURVEILLANCE_DU_SECTEUR_FINANCIER_CSSF("Commission de Surveillance du Secteur Financier (CSSF)"),
    @XmlEnumValue("Bank Negara Malaysia (Central Bank of Malaysia)")
    BANK_NEGARA_MALAYSIA_CENTRAL_BANK_OF_MALAYSIA("Bank Negara Malaysia (Central Bank of Malaysia)"),
    @XmlEnumValue("Securities Commission (Suruhanjaya Sekuriti)")
    SECURITIES_COMMISSION_SURUHANJAYA_SEKURITI("Securities Commission (Suruhanjaya Sekuriti)"),
    @XmlEnumValue("Autoriteit Financi\u00eble Markten (AFM) (Netherlands Authority for the Financial Markets)")
    AUTORITEIT_FINANCI_LE_MARKTEN_AFM_NETHERLANDS_AUTHORITY_FOR_THE_FINANCIAL_MARKETS("Autoriteit Financi\u00eble Markten (AFM) (Netherlands Authority for the Financial Markets)"),
    @XmlEnumValue("De Nederlandsche Bank")
    DE_NEDERLANDSCHE_BANK("De Nederlandsche Bank"),
    @XmlEnumValue("Pensioen & Verzekeringskamer")
    PENSIOEN_VERZEKERINGSKAMER("Pensioen & Verzekeringskamer"),
    @XmlEnumValue("Ministry of Economic Development")
    MINISTRY_OF_ECONOMIC_DEVELOPMENT("Ministry of Economic Development"),
    @XmlEnumValue("Reserve Bank of New Zealand")
    RESERVE_BANK_OF_NEW_ZEALAND("Reserve Bank of New Zealand"),
    @XmlEnumValue("Securities Commission")
    SECURITIES_COMMISSION("Securities Commission"),
    @XmlEnumValue("Insurance and Superannuation Unit (ISU)")
    INSURANCE_AND_SUPERANNUATION_UNIT_ISU("Insurance and Superannuation Unit (ISU)"),
    @XmlEnumValue("Financial service providers")
    FINANCIAL_SERVICE_PROVIDERS("Financial service providers"),
    @XmlEnumValue("Finanstilsynet (formerly Kredittilsynet) (Financial Supervisory Authority)")
    FINANSTILSYNET_FORMERLY_KREDITTILSYNET_FINANCIAL_SUPERVISORY_AUTHORITY("Finanstilsynet (formerly Kredittilsynet) (Financial Supervisory Authority)"),
    @XmlEnumValue("Narodowy Bank Polski (National Bank of Poland)")
    NARODOWY_BANK_POLSKI_NATIONAL_BANK_OF_POLAND("Narodowy Bank Polski (National Bank of Poland)"),
    @XmlEnumValue("Polish Financial Supervision Authority")
    POLISH_FINANCIAL_SUPERVISION_AUTHORITY("Polish Financial Supervision Authority"),
    @XmlEnumValue("The Polish Securities and Exchange Commission (Komisja Papier\u00f3w Warto\u015bciowych i Gie\u0142d)")
    THE_POLISH_SECURITIES_AND_EXCHANGE_COMMISSION_KOMISJA_PAPIER_W_WARTO\u015aCIOWYCH_I_GIE\u0141D("The Polish Securities and Exchange Commission (Komisja Papier\u00f3w Warto\u015bciowych i Gie\u0142d)"),
    @XmlEnumValue("Banco de Portugal")
    BANCO_DE_PORTUGAL("Banco de Portugal"),
    @XmlEnumValue("Comiss\u00e3o do Mercado de Valores Mobili\u00e1rios (CMVM) (Portuguese Securities Market Commission)")
    COMISS_O_DO_MERCADO_DE_VALORES_MOBILI_RIOS_CMVM_PORTUGUESE_SECURITIES_MARKET_COMMISSION("Comiss\u00e3o do Mercado de Valores Mobili\u00e1rios (CMVM) (Portuguese Securities Market Commission)"),
    @XmlEnumValue("Instituto de Seguros de Portugal (Portuguese Insurance Institute)")
    INSTITUTO_DE_SEGUROS_DE_PORTUGAL_PORTUGUESE_INSURANCE_INSTITUTE("Instituto de Seguros de Portugal (Portuguese Insurance Institute)"),
    @XmlEnumValue("National Bank Of Romania")
    NATIONAL_BANK_OF_ROMANIA("National Bank Of Romania"),
    @XmlEnumValue("Insurance Supervisory Commission")
    INSURANCE_SUPERVISORY_COMMISSION("Insurance Supervisory Commission"),
    @XmlEnumValue("Romanian National Securities Commission")
    ROMANIAN_NATIONAL_SECURITIES_COMMISSION("Romanian National Securities Commission"),
    @XmlEnumValue("Monetary Authority of Singapore (MAS)")
    MONETARY_AUTHORITY_OF_SINGAPORE_MAS("Monetary Authority of Singapore (MAS)"),
    @XmlEnumValue("National Bank of Slovakia")
    NATIONAL_BANK_OF_SLOVAKIA("National Bank of Slovakia"),
    @XmlEnumValue("Bank of Slovenia")
    BANK_OF_SLOVENIA("Bank of Slovenia"),
    @XmlEnumValue("Insurance Supervision Agency")
    INSURANCE_SUPERVISION_AGENCY("Insurance Supervision Agency"),
    @XmlEnumValue("Securities Market Agency")
    SECURITIES_MARKET_AGENCY("Securities Market Agency"),
    @XmlEnumValue("South African Reserve Bank")
    SOUTH_AFRICAN_RESERVE_BANK("South African Reserve Bank"),
    @XmlEnumValue("Financial Services Board")
    FINANCIAL_SERVICES_BOARD("Financial Services Board"),
    @XmlEnumValue("Financial Supervisory Commission / Financial Supervisory Service")
    FINANCIAL_SUPERVISORY_COMMISSION_FINANCIAL_SUPERVISORY_SERVICE("Financial Supervisory Commission / Financial Supervisory Service"),
    @XmlEnumValue("Banco de Espa\u00f1a")
    BANCO_DE_ESPA_A("Banco de Espa\u00f1a"),
    @XmlEnumValue("Comisi\u00f3n Nacional del Mercado de Valores (CNMV)")
    COMISI_N_NACIONAL_DEL_MERCADO_DE_VALORES_CNMV("Comisi\u00f3n Nacional del Mercado de Valores (CNMV)"),
    @XmlEnumValue("General Directorate of Insurance and Pension Funds (Direcci\u00f3n General de Seguros y Fondos de Pensiones)")
    GENERAL_DIRECTORATE_OF_INSURANCE_AND_PENSION_FUNDS_DIRECCI_N_GENERAL_DE_SEGUROS_Y_FONDOS_DE_PENSIONES("General Directorate of Insurance and Pension Funds (Direcci\u00f3n General de Seguros y Fondos de Pensiones)"),
    @XmlEnumValue("Finansinspektionen (Swedish Financial Supervisory Authority)")
    FINANSINSPEKTIONEN_SWEDISH_FINANCIAL_SUPERVISORY_AUTHORITY("Finansinspektionen (Swedish Financial Supervisory Authority)"),
    @XmlEnumValue("Financial Market Supervisory Authority (FINMA)")
    FINANCIAL_MARKET_SUPERVISORY_AUTHORITY_FINMA("Financial Market Supervisory Authority (FINMA)"),
    @XmlEnumValue("Bundesamt f\u00fcr Privatversicherungen (BPV) (Federal Office of Private Insurance)")
    BUNDESAMT_F_R_PRIVATVERSICHERUNGEN_BPV_FEDERAL_OFFICE_OF_PRIVATE_INSURANCE("Bundesamt f\u00fcr Privatversicherungen (BPV) (Federal Office of Private Insurance)"),
    @XmlEnumValue("Eidgenoessische Finanzmarktaufsicht (Swiss Federal Banking Commission)")
    EIDGENOESSISCHE_FINANZMARKTAUFSICHT_SWISS_FEDERAL_BANKING_COMMISSION("Eidgenoessische Finanzmarktaufsicht (Swiss Federal Banking Commission)"),
    @XmlEnumValue("Financial Conduct Authority (FCA)")
    FINANCIAL_CONDUCT_AUTHORITY_FCA("Financial Conduct Authority (FCA)"),
    @XmlEnumValue("Prudential Regulation Authority (PRA) (Now FCA)")
    PRUDENTIAL_REGULATION_AUTHORITY_PRA_NOW_FCA("Prudential Regulation Authority (PRA) (Now FCA)"),
    @XmlEnumValue("Financial Services Authority (FSA)")
    FINANCIAL_SERVICES_AUTHORITY_FSA("Financial Services Authority (FSA)"),
    @XmlEnumValue("The Pensions Regulator")
    THE_PENSIONS_REGULATOR("The Pensions Regulator"),
    @XmlEnumValue("Board of Directors of the Federal Deposit Insurance Corporation (FDIC)")
    BOARD_OF_DIRECTORS_OF_THE_FEDERAL_DEPOSIT_INSURANCE_CORPORATION_FDIC("Board of Directors of the Federal Deposit Insurance Corporation (FDIC)"),
    @XmlEnumValue("Commodity Futures Trading Commission (CFTC)")
    COMMODITY_FUTURES_TRADING_COMMISSION_CFTC("Commodity Futures Trading Commission (CFTC)"),
    @XmlEnumValue("Federal Deposit Insurance Corporation (FDIC)")
    FEDERAL_DEPOSIT_INSURANCE_CORPORATION_FDIC("Federal Deposit Insurance Corporation (FDIC)"),
    @XmlEnumValue("Federal Housing Finance Board")
    FEDERAL_HOUSING_FINANCE_BOARD("Federal Housing Finance Board"),
    @XmlEnumValue("Federal Reserve System (FED)")
    FEDERAL_RESERVE_SYSTEM_FED("Federal Reserve System (FED)"),
    @XmlEnumValue("Financial Industry Regulatory Authority (FINRA)")
    FINANCIAL_INDUSTRY_REGULATORY_AUTHORITY_FINRA("Financial Industry Regulatory Authority (FINRA)"),
    @XmlEnumValue("Florida Office of Financial Regulation")
    FLORIDA_OFFICE_OF_FINANCIAL_REGULATION("Florida Office of Financial Regulation"),
    @XmlEnumValue("Municipal Securities Rulemarking Board")
    MUNICIPAL_SECURITIES_RULEMARKING_BOARD("Municipal Securities Rulemarking Board"),
    @XmlEnumValue("National Association of Insurance Commissioners (NAIC)")
    NATIONAL_ASSOCIATION_OF_INSURANCE_COMMISSIONERS_NAIC("National Association of Insurance Commissioners (NAIC)"),
    @XmlEnumValue("National Credit Union Administration (NCUA)")
    NATIONAL_CREDIT_UNION_ADMINISTRATION_NCUA("National Credit Union Administration (NCUA)"),
    @XmlEnumValue("National Futures Association (NFA)")
    NATIONAL_FUTURES_ASSOCIATION_NFA("National Futures Association (NFA)"),
    @XmlEnumValue("New York Department of Insurance")
    NEW_YORK_DEPARTMENT_OF_INSURANCE("New York Department of Insurance"),
    @XmlEnumValue("New York State Banking Department")
    NEW_YORK_STATE_BANKING_DEPARTMENT("New York State Banking Department"),
    @XmlEnumValue("Office of the Comptroller of the Currency (OCC)  / (OTS)")
    OFFICE_OF_THE_COMPTROLLER_OF_THE_CURRENCY_OCC_OTS("Office of the Comptroller of the Currency (OCC)  / (OTS)"),
    @XmlEnumValue("Securities and Exchange Commission (SEC)")
    SECURITIES_AND_EXCHANGE_COMMISSION_SEC("Securities and Exchange Commission (SEC)");
    private final String value;

    DictionaryRegulator(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DictionaryRegulator fromValue(String v) {
        for (DictionaryRegulator c: DictionaryRegulator.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
