//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DictionaryDesignation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DictionaryDesignation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Mr."/>
 *     &lt;enumeration value="Miss"/>
 *     &lt;enumeration value="Ms."/>
 *     &lt;enumeration value="Mrs."/>
 *     &lt;enumeration value="Dr."/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DictionaryDesignation")
@XmlEnum
public enum DictionaryDesignation {

    @XmlEnumValue("Mr.")
    MR("Mr."),
    @XmlEnumValue("Miss")
    MISS("Miss"),
    @XmlEnumValue("Ms.")
    MS("Ms."),
    @XmlEnumValue("Mrs.")
    MRS("Mrs."),
    @XmlEnumValue("Dr.")
    DR("Dr.");
    private final String value;

    DictionaryDesignation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DictionaryDesignation fromValue(String v) {
        for (DictionaryDesignation c: DictionaryDesignation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
