//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DictionaryContactRole.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DictionaryContactRole">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Primary Contact Person"/>
 *     &lt;enumeration value="Authorised Signatory"/>
 *     &lt;enumeration value="Compliance"/>
 *     &lt;enumeration value="Credit"/>
 *     &lt;enumeration value="Legal"/>
 *     &lt;enumeration value="Closer"/>
 *     &lt;enumeration value="Trader"/>
 *     &lt;enumeration value="Admin Agent"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DictionaryContactRole")
@XmlEnum
public enum DictionaryContactRole {

    @XmlEnumValue("Primary Contact Person")
    PRIMARY_CONTACT_PERSON("Primary Contact Person"),
    @XmlEnumValue("Authorised Signatory")
    AUTHORISED_SIGNATORY("Authorised Signatory"),
    @XmlEnumValue("Compliance")
    COMPLIANCE("Compliance"),
    @XmlEnumValue("Credit")
    CREDIT("Credit"),
    @XmlEnumValue("Legal")
    LEGAL("Legal"),
    @XmlEnumValue("Closer")
    CLOSER("Closer"),
    @XmlEnumValue("Trader")
    TRADER("Trader"),
    @XmlEnumValue("Admin Agent")
    ADMIN_AGENT("Admin Agent"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    DictionaryContactRole(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DictionaryContactRole fromValue(String v) {
        for (DictionaryContactRole c: DictionaryContactRole.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
