//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DictionaryKeyFinancialIndicator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DictionaryKeyFinancialIndicator">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Total Asset Size"/>
 *     &lt;enumeration value="Total Assets Under Management"/>
 *     &lt;enumeration value="Total Revenue"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DictionaryKeyFinancialIndicator")
@XmlEnum
public enum DictionaryKeyFinancialIndicator {

    @XmlEnumValue("Total Asset Size")
    TOTAL_ASSET_SIZE("Total Asset Size"),
    @XmlEnumValue("Total Assets Under Management")
    TOTAL_ASSETS_UNDER_MANAGEMENT("Total Assets Under Management"),
    @XmlEnumValue("Total Revenue")
    TOTAL_REVENUE("Total Revenue");
    private final String value;

    DictionaryKeyFinancialIndicator(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DictionaryKeyFinancialIndicator fromValue(String v) {
        for (DictionaryKeyFinancialIndicator c: DictionaryKeyFinancialIndicator.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
