//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Individual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Individual">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.markit.com}Entity">
 *       &lt;sequence>
 *         &lt;element name="designation" type="{http://www.markit.com}AttributeDictionaryDesignation" minOccurs="0"/>
 *         &lt;element name="firstName" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="middleName" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="lastName" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="gender" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="dob" type="{http://www.markit.com}AttributeDate" minOccurs="0"/>
 *         &lt;element name="aliases" type="{http://www.markit.com}AttributeString" minOccurs="0"/>
 *         &lt;element name="citizenship" type="{http://www.markit.com}IndividualCitizenship" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="governmentIDInfo" type="{http://www.markit.com}AttributeIndividualGovernmentIDInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Individual", propOrder = {
    "designation",
    "firstName",
    "middleName",
    "lastName",
    "gender",
    "dob",
    "aliases",
    "citizenship",
    "governmentIDInfo"
})
public class Individual
    extends Entity
{

    protected AttributeDictionaryDesignation designation;
    protected AttributeString firstName;
    protected AttributeString middleName;
    protected AttributeString lastName;
    protected AttributeString gender;
    protected AttributeDate dob;
    protected AttributeString aliases;
    protected List<IndividualCitizenship> citizenship;
    protected List<AttributeIndividualGovernmentIDInfo> governmentIDInfo;

    /**
     * Gets the value of the designation property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDictionaryDesignation }
     *     
     */
    public AttributeDictionaryDesignation getDesignation() {
        return designation;
    }

    /**
     * Sets the value of the designation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDictionaryDesignation }
     *     
     */
    public void setDesignation(AttributeDictionaryDesignation value) {
        this.designation = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setFirstName(AttributeString value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setMiddleName(AttributeString value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setLastName(AttributeString value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setGender(AttributeString value) {
        this.gender = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDate }
     *     
     */
    public AttributeDate getDob() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDate }
     *     
     */
    public void setDob(AttributeDate value) {
        this.dob = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeString }
     *     
     */
    public AttributeString getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeString }
     *     
     */
    public void setAliases(AttributeString value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the citizenship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citizenship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitizenship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndividualCitizenship }
     * 
     * 
     */
    public List<IndividualCitizenship> getCitizenship() {
        if (citizenship == null) {
            citizenship = new ArrayList<IndividualCitizenship>();
        }
        return this.citizenship;
    }

    /**
     * Gets the value of the governmentIDInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the governmentIDInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGovernmentIDInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeIndividualGovernmentIDInfo }
     * 
     * 
     */
    public List<AttributeIndividualGovernmentIDInfo> getGovernmentIDInfo() {
        if (governmentIDInfo == null) {
            governmentIDInfo = new ArrayList<AttributeIndividualGovernmentIDInfo>();
        }
        return this.governmentIDInfo;
    }

    public void setCitizenship(List<IndividualCitizenship> value) {
        this.citizenship = value;
    }

    public void setGovernmentIDInfo(List<AttributeIndividualGovernmentIDInfo> value) {
        this.governmentIDInfo = value;
    }

}
