//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 11:38:43 AM IST 
//


package com.headstrong.npi.raas.cobs.xml.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.headstrong.npi.raas.cobs.xml.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Case_QNAME = new QName("http://www.markit.com", "case");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.headstrong.npi.raas.cobs.xml.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttributeIndividualGovernmentIDInfo }
     * 
     */
    public AttributeIndividualGovernmentIDInfo createAttributeIndividualGovernmentIDInfo() {
        return new AttributeIndividualGovernmentIDInfo();
    }

    /**
     * Create an instance of {@link AttributeAddress }
     * 
     */
    public AttributeAddress createAttributeAddress() {
        return new AttributeAddress();
    }

    /**
     * Create an instance of {@link AttributeCompanyBeneficialOwner }
     * 
     */
    public AttributeCompanyBeneficialOwner createAttributeCompanyBeneficialOwner() {
        return new AttributeCompanyBeneficialOwner();
    }

    /**
     * Create an instance of {@link CompanyBusinessActivityIndustryCode }
     * 
     */
    public CompanyBusinessActivityIndustryCode createCompanyBusinessActivityIndustryCode() {
        return new CompanyBusinessActivityIndustryCode();
    }

    /**
     * Create an instance of {@link AttributeCompanyControllerDirector }
     * 
     */
    public AttributeCompanyControllerDirector createAttributeCompanyControllerDirector() {
        return new AttributeCompanyControllerDirector();
    }

    /**
     * Create an instance of {@link CompanyFinancialInfo }
     * 
     */
    public CompanyFinancialInfo createCompanyFinancialInfo() {
        return new CompanyFinancialInfo();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link AttributeLong }
     * 
     */
    public AttributeLong createAttributeLong() {
        return new AttributeLong();
    }

    /**
     * Create an instance of {@link AttributeCompanyGovernmentIDInfo }
     * 
     */
    public AttributeCompanyGovernmentIDInfo createAttributeCompanyGovernmentIDInfo() {
        return new AttributeCompanyGovernmentIDInfo();
    }

    /**
     * Create an instance of {@link AttributeDictionaryKeyFinancialIndicator }
     * 
     */
    public AttributeDictionaryKeyFinancialIndicator createAttributeDictionaryKeyFinancialIndicator() {
        return new AttributeDictionaryKeyFinancialIndicator();
    }

    /**
     * Create an instance of {@link AttributeDictionaryIndustryCode }
     * 
     */
    public AttributeDictionaryIndustryCode createAttributeDictionaryIndustryCode() {
        return new AttributeDictionaryIndustryCode();
    }

    /**
     * Create an instance of {@link AttributeCompanyRelatedParty }
     * 
     */
    public AttributeCompanyRelatedParty createAttributeCompanyRelatedParty() {
        return new AttributeCompanyRelatedParty();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link AttributeCompanyContact }
     * 
     */
    public AttributeCompanyContact createAttributeCompanyContact() {
        return new AttributeCompanyContact();
    }

    /**
     * Create an instance of {@link CompanyIndustryIdentifier }
     * 
     */
    public CompanyIndustryIdentifier createCompanyIndustryIdentifier() {
        return new CompanyIndustryIdentifier();
    }

    /**
     * Create an instance of {@link AttributeCompanyBusinessActivityIndustryCode }
     * 
     */
    public AttributeCompanyBusinessActivityIndustryCode createAttributeCompanyBusinessActivityIndustryCode() {
        return new AttributeCompanyBusinessActivityIndustryCode();
    }

    /**
     * Create an instance of {@link AttributeEntity }
     * 
     */
    public AttributeEntity createAttributeEntity() {
        return new AttributeEntity();
    }

    /**
     * Create an instance of {@link AttributeDouble }
     * 
     */
    public AttributeDouble createAttributeDouble() {
        return new AttributeDouble();
    }

    /**
     * Create an instance of {@link AttributeDictionaryOwnershipType }
     * 
     */
    public AttributeDictionaryOwnershipType createAttributeDictionaryOwnershipType() {
        return new AttributeDictionaryOwnershipType();
    }

    /**
     * Create an instance of {@link CompanyLicenseInfo }
     * 
     */
    public CompanyLicenseInfo createCompanyLicenseInfo() {
        return new CompanyLicenseInfo();
    }

    /**
     * Create an instance of {@link CompanyGovernmentIDInfo }
     * 
     */
    public CompanyGovernmentIDInfo createCompanyGovernmentIDInfo() {
        return new CompanyGovernmentIDInfo();
    }

    /**
     * Create an instance of {@link CompanyEntityName }
     * 
     */
    public CompanyEntityName createCompanyEntityName() {
        return new CompanyEntityName();
    }

    /**
     * Create an instance of {@link Individual }
     * 
     */
    public Individual createIndividual() {
        return new Individual();
    }

    /**
     * Create an instance of {@link ChallengeCase }
     * 
     */
    public ChallengeCase createChallengeCase() {
        return new ChallengeCase();
    }

    /**
     * Create an instance of {@link AttributeCompanyBusinessActivity }
     * 
     */
    public AttributeCompanyBusinessActivity createAttributeCompanyBusinessActivity() {
        return new AttributeCompanyBusinessActivity();
    }

    /**
     * Create an instance of {@link CompanyBearerShare }
     * 
     */
    public CompanyBearerShare createCompanyBearerShare() {
        return new CompanyBearerShare();
    }

    /**
     * Create an instance of {@link AttributeDictionaryGovernmentIssuedIDType }
     * 
     */
    public AttributeDictionaryGovernmentIssuedIDType createAttributeDictionaryGovernmentIssuedIDType() {
        return new AttributeDictionaryGovernmentIssuedIDType();
    }

    /**
     * Create an instance of {@link AttributeCompanyEntityName }
     * 
     */
    public AttributeCompanyEntityName createAttributeCompanyEntityName() {
        return new AttributeCompanyEntityName();
    }

    /**
     * Create an instance of {@link AttributeBoolean }
     * 
     */
    public AttributeBoolean createAttributeBoolean() {
        return new AttributeBoolean();
    }

    /**
     * Create an instance of {@link AttributeDate }
     * 
     */
    public AttributeDate createAttributeDate() {
        return new AttributeDate();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link CompanyControllerDirector }
     * 
     */
    public CompanyControllerDirector createCompanyControllerDirector() {
        return new CompanyControllerDirector();
    }

    /**
     * Create an instance of {@link CompanyContact }
     * 
     */
    public CompanyContact createCompanyContact() {
        return new CompanyContact();
    }

    /**
     * Create an instance of {@link AttributeCompanyGovernmentOwnership }
     * 
     */
    public AttributeCompanyGovernmentOwnership createAttributeCompanyGovernmentOwnership() {
        return new AttributeCompanyGovernmentOwnership();
    }

    /**
     * Create an instance of {@link AttributeDictionaryCurrency }
     * 
     */
    public AttributeDictionaryCurrency createAttributeDictionaryCurrency() {
        return new AttributeDictionaryCurrency();
    }

    /**
     * Create an instance of {@link IndividualCitizenship }
     * 
     */
    public IndividualCitizenship createIndividualCitizenship() {
        return new IndividualCitizenship();
    }

    /**
     * Create an instance of {@link AttributeDictionaryIndividualGovernmentIdType }
     * 
     */
    public AttributeDictionaryIndividualGovernmentIdType createAttributeDictionaryIndividualGovernmentIdType() {
        return new AttributeDictionaryIndividualGovernmentIdType();
    }

    /**
     * Create an instance of {@link AttributeCompanyRegulatedInfo }
     * 
     */
    public AttributeCompanyRegulatedInfo createAttributeCompanyRegulatedInfo() {
        return new AttributeCompanyRegulatedInfo();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AttributeCompany }
     * 
     */
    public AttributeCompany createAttributeCompany() {
        return new AttributeCompany();
    }

    /**
     * Create an instance of {@link FormationCase }
     * 
     */
    public FormationCase createFormationCase() {
        return new FormationCase();
    }

    /**
     * Create an instance of {@link AttributeString }
     * 
     */
    public AttributeString createAttributeString() {
        return new AttributeString();
    }

    /**
     * Create an instance of {@link AttributeCompanyBearerShare }
     * 
     */
    public AttributeCompanyBearerShare createAttributeCompanyBearerShare() {
        return new AttributeCompanyBearerShare();
    }

    /**
     * Create an instance of {@link AttributeCompanyFormation }
     * 
     */
    public AttributeCompanyFormation createAttributeCompanyFormation() {
        return new AttributeCompanyFormation();
    }

    /**
     * Create an instance of {@link AttributeEntityStructure }
     * 
     */
    public AttributeEntityStructure createAttributeEntityStructure() {
        return new AttributeEntityStructure();
    }

    /**
     * Create an instance of {@link CompanyAML }
     * 
     */
    public CompanyAML createCompanyAML() {
        return new CompanyAML();
    }

    /**
     * Create an instance of {@link CompanyRelatedParty }
     * 
     */
    public CompanyRelatedParty createCompanyRelatedParty() {
        return new CompanyRelatedParty();
    }

    /**
     * Create an instance of {@link FullReviewCase }
     * 
     */
    public FullReviewCase createFullReviewCase() {
        return new FullReviewCase();
    }

    /**
     * Create an instance of {@link AttributeCompanyFinancialInfo }
     * 
     */
    public AttributeCompanyFinancialInfo createAttributeCompanyFinancialInfo() {
        return new AttributeCompanyFinancialInfo();
    }

    /**
     * Create an instance of {@link AttributeDictionaryExchange }
     * 
     */
    public AttributeDictionaryExchange createAttributeDictionaryExchange() {
        return new AttributeDictionaryExchange();
    }

    /**
     * Create an instance of {@link CompanyCountryOfBusiness }
     * 
     */
    public CompanyCountryOfBusiness createCompanyCountryOfBusiness() {
        return new CompanyCountryOfBusiness();
    }

    /**
     * Create an instance of {@link AttributeDictionaryCountry }
     * 
     */
    public AttributeDictionaryCountry createAttributeDictionaryCountry() {
        return new AttributeDictionaryCountry();
    }

    /**
     * Create an instance of {@link AttributeCompanyAML }
     * 
     */
    public AttributeCompanyAML createAttributeCompanyAML() {
        return new AttributeCompanyAML();
    }

    /**
     * Create an instance of {@link CompanyListedInfo }
     * 
     */
    public CompanyListedInfo createCompanyListedInfo() {
        return new CompanyListedInfo();
    }

    /**
     * Create an instance of {@link CompanyFormation }
     * 
     */
    public CompanyFormation createCompanyFormation() {
        return new CompanyFormation();
    }

    /**
     * Create an instance of {@link AttributeDictionaryBookingJurisdiction }
     * 
     */
    public AttributeDictionaryBookingJurisdiction createAttributeDictionaryBookingJurisdiction() {
        return new AttributeDictionaryBookingJurisdiction();
    }

    /**
     * Create an instance of {@link AttributeDictionaryIndustryCodeType }
     * 
     */
    public AttributeDictionaryIndustryCodeType createAttributeDictionaryIndustryCodeType() {
        return new AttributeDictionaryIndustryCodeType();
    }

    /**
     * Create an instance of {@link AttributeDictionaryState }
     * 
     */
    public AttributeDictionaryState createAttributeDictionaryState() {
        return new AttributeDictionaryState();
    }

    /**
     * Create an instance of {@link AttributeCompanyCountryOfBusiness }
     * 
     */
    public AttributeCompanyCountryOfBusiness createAttributeCompanyCountryOfBusiness() {
        return new AttributeCompanyCountryOfBusiness();
    }

    /**
     * Create an instance of {@link AttributeEntityType }
     * 
     */
    public AttributeEntityType createAttributeEntityType() {
        return new AttributeEntityType();
    }

    /**
     * Create an instance of {@link CompanyRegulatedInfo }
     * 
     */
    public CompanyRegulatedInfo createCompanyRegulatedInfo() {
        return new CompanyRegulatedInfo();
    }

    /**
     * Create an instance of {@link AttributeCompanyListedInfo }
     * 
     */
    public AttributeCompanyListedInfo createAttributeCompanyListedInfo() {
        return new AttributeCompanyListedInfo();
    }

    /**
     * Create an instance of {@link AttributeCompanyLicenseInfo }
     * 
     */
    public AttributeCompanyLicenseInfo createAttributeCompanyLicenseInfo() {
        return new AttributeCompanyLicenseInfo();
    }

    /**
     * Create an instance of {@link AttributeCompanyIndustryIdentifier }
     * 
     */
    public AttributeCompanyIndustryIdentifier createAttributeCompanyIndustryIdentifier() {
        return new AttributeCompanyIndustryIdentifier();
    }

    /**
     * Create an instance of {@link CompanyBusinessActivity }
     * 
     */
    public CompanyBusinessActivity createCompanyBusinessActivity() {
        return new CompanyBusinessActivity();
    }

    /**
     * Create an instance of {@link CompanyBeneficialOwner }
     * 
     */
    public CompanyBeneficialOwner createCompanyBeneficialOwner() {
        return new CompanyBeneficialOwner();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AttributeDictionaryRegulator }
     * 
     */
    public AttributeDictionaryRegulator createAttributeDictionaryRegulator() {
        return new AttributeDictionaryRegulator();
    }

    /**
     * Create an instance of {@link IndividualGovernmentIDInfo }
     * 
     */
    public IndividualGovernmentIDInfo createIndividualGovernmentIDInfo() {
        return new IndividualGovernmentIDInfo();
    }

    /**
     * Create an instance of {@link AttributeDictionaryDesignation }
     * 
     */
    public AttributeDictionaryDesignation createAttributeDictionaryDesignation() {
        return new AttributeDictionaryDesignation();
    }

    /**
     * Create an instance of {@link CompanyGovernmentOwnership }
     * 
     */
    public CompanyGovernmentOwnership createCompanyGovernmentOwnership() {
        return new CompanyGovernmentOwnership();
    }

    /**
     * Create an instance of {@link AuditRecord }
     * 
     */
    public AuditRecord createAuditRecord() {
        return new AuditRecord();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Case }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.markit.com", name = "case")
    public JAXBElement<Case> createCase(Case value) {
        return new JAXBElement<Case>(_Case_QNAME, Case.class, null, value);
    }

}
